### ISSUE TITLE
chatbot:Operation returned an invalid status code 'Gone' 

### ISSUE THREAD

**Issue by ashok-dot** [microsoft/botframework-sdk#6119] opened 2020-11-24 23:18 UTC
Bot Info
Bot Framework SDK Version: 4.3.2
SDK Platform: .NET Core 3.1
Active Channels: Microsoft Teams Chatbot
Deployment Environment: Azure App Service (West Europe)

I am facing the below issue after migrated LUIS ,it changed appkey,appID and hostname , i have configured correctly and save. i was restart machine ,i am check local emulator not working,then i was deployed to azure server checked chatbot still showing some error message " Operation returned an invalid status code 'Gone'".

var luisApplication = new LuisApplication(
Environment.GetEnvironmentVariable("LuisAppId"),
Environment.GetEnvironmentVariable("LuisAPIKey"),
Environment.GetEnvironmentVariable("LuisAPIHostName")
);

            var recognizer = new LuisRecognizer(luisApplication);
Error Message
Operation returned an invalid status code 'Gone'

**Comment by jwiley84** [comment] 2020-11-25 18:29
Closing as a duplicate of https://github.com/microsoft/BotFramework-Services/issues/268

and a duplicate of this: https://github.com/microsoft/botframework-sdk/issues/6118

**Closed by jwiley84** 2020-11-25 18:29 UTC
Labels: Bot Services, bug, customer-replied-to, customer-reported, needs-triage

**Comment by ashok-dot** [comment] 2020-11-26 01:29
Bot Info:

Bot Framework SDK Version: 4.3.2

SDK Platform: .NET Core 3.1emphasized text

Active Channels: Microsoft Teams Chatbot

Deployment Environment: Azure App Service (West Europe)

I am facing the below issue after migrated LUIS ,it changed appkey,appID and hostname , I have configured correctly and save. I was restart machine ,I am check local emulator not working, then I was deployed to azure server checked chatbot still showing some error message " Operation returned an invalid status code 'Gone'".

// Create the LUIS settings from configuration.
//Get all the LUIS related details from Env variables.

var luisApplication = new LuisApplication(
    Environment.GetEnvironmentVariable("LuisAppId"),
    Environment.GetEnvironmentVariable("LuisAPIKey"),
    Environment.GetEnvironmentVariable("LuisAPIHostName")
  );

var recognizer = new LuisRecognizer(luisApplication);
The actual call to LUIS. This will retrun the identified intent and entities recognizerResult = awaitrecognizer.RecognizeAsync(turnContext,cancellationToken);

while response back to "The application d1e6b8a0-47bb-4890-9250-6fb3f2d2bb62 is not published in slot Production"
