### ISSUE TITLE
onMemberAdded missing locale field for directline or Teams

### ISSUE THREAD

**Issue by ubreddy** [microsoft/botframework-sdk#6484] opened 2022-03-14 10:42 UTC
## Version
What package version of the SDK are you using.
4

## Describe the bug
Give a clear and concise description of what the bug is.
The payload received for onMemberAdded does not contain locale
```json
{
"type":"conversationUpdate","id":"HeRc6Qw5HJI",
"timestamp":"2022-03-14T05:47:25.697Z",
"serviceUrl":"https://directline.botframework.com/",
"channelId":"directline",
"from":{"id":"164933c1-1aab-231a-ac74-a2fc9cc6599b"},
"conversation":{"id":"6X0upWnRqm4CQfXPKSuUfK-us"},
"recipient":{"id":"testbabb@ePKtrX1b6v0","name":"KP5"},
"membersAdded":[{"id":"testabb@ePKtrX1b6v0","name":"KP5"},
{"id":"164933c1-1aab-46da-ac74-a2fc9cc6599b"}],
"rawTimestamp":"2022-03-14T05:47:25.6974274Z",
"callerId":"urn:botframework:azure"
}
```
## Expected behavior
Give a clear and concise description of what you expected to happen.
Expected to receive locale information so that the welcome message could be localised.
Same payload for Teams too.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by ramfattah** [comment] 2022-03-14 21:33
Hi @ubreddy

Are you facing this problem in webchat? if so, have you tried providing the locale using "conversationStartProperties"?
```diff
        window.WebChat.renderWebChat({
          directLine: window.WebChat.createDirectLine({
+            conversationStartProperties: {
+              locale: `${window.navigator.language}` 
+            },
            token
          }),
        },
          document.getElementById('webchat'),
        );
```

Reference here https://github.com/microsoft/BotFramework-Composer/issues/8886#issuecomment-1014947459

Let me know if this worked. Thanks.

**Comment by ubreddy** [comment] 2022-03-15 04:14
Thanks @ramfattah. Yes. I did that for directline... using browser detect language capability. 
but for teams I am unable to figure out how to set this up.

**Comment by ramfattah** [comment] 2022-03-16 16:06
Hi @ubreddy 

For clarity: a couple of questions regarding your bot:
* Are you using composer or SDK?
* What programming language did you pick?

**Comment by udaya-reddy** [comment] 2022-03-21 05:18
I am using SDK version 4.
javascript.

**Comment by ubreddy** [comment] 2022-03-24 09:54
> Hi @ubreddy
> 
> For clarity: a couple of questions regarding your bot:
> 
> * Are you using composer or SDK?
> * What programming language did you pick?

SDK version 4  of nodejs.

**Comment by ramfattah** [comment] 2022-03-24 17:38
@udaya-reddy @ubreddy, Thank you for the update. I'm investigating this.

**Comment by ramfattah** [comment] 2022-03-30 21:21
Closing this issue as it is not a bug in the SDK.

**Closed by ramfattah** 2022-03-30 21:21 UTC
Labels: customer-replied-to, customer-reported, Bot Services
