### ISSUE TITLE
Unstable error "BadGateway" at sending activities

### ISSUE THREAD

**Issue by WhiteCyClop** [microsoft/botframework-sdk#6302] opened 2021-05-29 12:18 UTC
## Version
4.10.3

## Describe the bug
A few weeks ago I noticed that sometimes my bot throws an error "Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'BadGateway'" when it tried to send activity to user. This is the stack of error:

```
Microsoft.Bot.Schema.ErrorResponseException: Operation returned an invalid status code 'BadGateway'
at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivityAsync(IConversations operations, String conversationId, String activityId, Activity activity, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.BotFrameworkAdapter.SendActivitiesAsync(ITurnContext turnContext, Activity[] activities, CancellationToken cancellationToken)
at Microsoft.Bot.Builder.TurnContext.<>c__DisplayClass29_0.<<SendActivitiesAsync>g__SendActivitiesThroughAdapter|1>d.MoveNext()
```

The strangest thing is unstable behavior of this error. For example, a bot can send several adaptive cards to the user one after one within several seconds and for 9 out of 10 there is no any problem, but for the one in the middle of this pool there is an error.

**Comment by v-kydela** [comment] 2021-05-31 17:16
Thank you for the report, @WhiteCyClop. I would like to help and I have a few questions.

1. Is this a C# bot?
2. What channel are you using?
3. Can you provide some example code to help us reproduce the exception?
4. What are your repro steps?

**Comment by WhiteCyClop** [comment] 2021-05-31 17:58
@v-kydela Thank you for your reply.

1. Yes, this is a C# bot (.Net Core 3.1)
2. I'm using MS Teams Channel
3. For example I use this code to send activity to user:
```
private async Task<DialogTurnResult> SendActivity(DialogContext outerDc,
                                                  IActivity activity,
                                                  bool replace,
                                                  CancellationToken cancellationToken)
{
    if (replace && !string.IsNullOrWhiteSpace(outerDc.Context.Activity.ReplyToId))
    {
        if (outerDc.Context.Activity.Type == activity.Type)
        {
            activity.Id = outerDc.Context.Activity.ReplyToId;
            await outerDc.Context.UpdateActivityAsync(activity, cancellationToken);
        }
        else
        {
            await outerDc.Context.DeleteActivityAsync(outerDc.Context.Activity.ReplyToId, cancellationToken);
            await outerDc.Context.SendActivityAsync(activity, cancellationToken);
        }
    }
    else
    {
        await outerDc.Context.SendActivityAsync(activity, cancellationToken);
    }

    return await outerDc.EndDialogAsync();
}
```
And exception is throwed by SendActivityAsync-method of the dialog context.
4. I don't know how to specifically reproduce this error, I just see it at logs of my app almost every day.

**Comment by v-kydela** [comment] 2021-05-31 18:33
@WhiteCyClop - I notice that your code deletes and updates activities. Is it possible that the exception is caused by trying to delete or update an activity that has already been deleted?

**Comment by WhiteCyClop** [comment] 2021-05-31 18:39
No, I have this problem with cases when "replace" parameter is false. My bot just tries to send new activity.

**Comment by v-kydela** [comment] 2021-05-31 20:30
@WhiteCyClop - Can you give an example of an activity that produces the exception? Also, what type of conversation does it happen in?

@microsoft/teams - Can you provide any assistance regarding why Teams might return a bad gateway error?

**Comment by v-kydela** [comment] 2021-05-31 20:36
@WhiteCyClop - Can you give an example of an activity that produces the exception? Could there be something wrong with the conversation ID, the recipient ID, or the service URL? Also, what type of conversation does it happen in?

**Comment by WhiteCyClop** [comment] 2021-06-01 04:19
For example, there was an exception for this adaptive card:
```
{
  "type": "AdaptiveCard",
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.2",
  "body": [
    {
      "type": "ColumnSet",
      "columns": [
        {
          "type": "Column",
          "width": "stretch",
          "items": [
            {
              "type": "TextBlock",
              "size": "Medium",
              "weight": "Bolder",
              "text": "Остаток отпуска",
              "wrap": true
            }
          ],
          "verticalContentAlignment": "Center"
        }
      ]
    },
    {
      "type": "Container",
      "items": [
        {
          "type": "TextBlock",
          "text": "",
          "id": "textMessage",
          "wrap": true
        },
        {
          "type": "Container",
          "items": [
            {
              "type": "FactSet",
              "id": "factVacationList",
              "facts": [
                {
                  "title": "Основной",
                  "value": "2 дн."
                },
                {
                  "title": "Дополнительный",
                  "value": "4 дн."
                }
              ]
            }
          ]
        },
        {
          "type": "TextBlock",
          "text": "Если вы хотите уточнить/проверить остаток отпуска, обратитесь к вашему менеджеру по персоналу.",
          "wrap": true
        },
        {
          "type": "TextBlock",
          "text": "Вы хотите оформить заявление на отпуск?",
          "wrap": true
        }
      ]
    },
    {
      "type": "ActionSet",
      "actions": [
        {
          "type": "Action.Submit",
          "title": "Оформить",
          "style": "positive",
          "data": {
            "msteams": {
              "type": "invoke"
            },
            "dialogId": "SelectVacationTypeDialog",
            "VacationType": 1
          }
        },
        {
          "type": "Action.Submit",
          "title": "Не нужно",
          "style": "destructive",
          "data": {
            "msteams": {
              "type": "invoke"
            },
            "dialogId": "TopLevelDialog"
          }
        }
      ]
    }
  ]
}
```
But also I have this problem with another cards and just messages. 

I don't think that there can be something wrong with conversation ID, the recipient ID, or the service URL, because the error may appear a second after the successful sending of data to the same user, and after it everything is also sent without errors. 

Type of conversation is personal chatting with bot, if I understood question correctly.

**Comment by Wajeed-msft** [comment] 2021-06-01 04:28
@WhiteCyClop - As there are no specific repro streps, could you please share the Bot Id and timestamp of the issue so that we can check logs?

**Comment by WhiteCyClop** [comment] 2021-06-01 05:16
Yes, Bot Id is "575a5ae9-e730-416a-8c23-9704f9cb2664" and timestamp is [2021-05-28 11:00:45.779 +00:00]

**Comment by v-kydela** [comment] 2021-06-02 16:18
@WhiteCyClop 

> the error may appear a second after the successful sending of data to the same user, and after it everything is also sent without errors.

Does this mean the bad gateway errors you're observing aren't actually preventing messages from going through? Are you saying you just want to know why you're seeing them in your logs even though they aren't interfering with the conversation?

**Comment by WhiteCyClop** [comment] 2021-06-02 17:30
Unfortunately, these errors are actually preventing messages from going through. When I told about successful sending, I mean that there were several messages and most of them were sent to the user normally, but just one can threw exception.

**Comment by Wajeed-msft** [comment] 2021-06-04 05:30
@WhiteCyClop - could you please confirm if this is happening for same user all the time or it's different?

I looked at logs and see some errors related to App Permissions policies. checking this further with engineering team. I'll keep you posted.

**Comment by Wajeed-msft** [comment] 2021-06-04 05:34
@WhiteCyClop - I have copied this issue over to Microsoft Teams side for tracking purpose. Here: https://github.com/MicrosoftDocs/msteams-docs/issues/3561

@v-kydela - could you please help to close this one from this repo?

**Comment by WhiteCyClop** [comment] 2021-06-04 07:02
@Wajeed-msft - This error is happening for different users

**Closed** 2021-06-04 16:46 UTC
Labels: Area: Teams, Bot Services, bug, customer-replied-to, customer-reported, needs-triage

**Comment by danghoanghai** [comment] 2023-10-31 08:47
hi, I am facing this issue again from about 10 days ago until now. Please help me check
