### ISSUE TITLE
Accessing a property field named with a dash "-" fails

### ISSUE THREAD

**Issue by bewillet** [microsoft/botframework-sdk#6330] opened 2021-06-22 19:17 UTC
## Describe the bug
Accessing the property field within the response message is not possible for the following:
"${conversation.ocvoices.en-US.d365_oc_ivrvoicename}"

We are storing the locale code "en-US" as an attribute in a Json payload, but are unable to access the above path because of the "-" in the field name.

## Version
2.0.0

## To Reproduce

1. In Composer set a conversation property with an object

![image](https://user-images.githubusercontent.com/75699913/122984476-e6a02a00-d351-11eb-866b-ee86b3ab76f2.png)
![image](https://user-images.githubusercontent.com/75699913/122984567-03d4f880-d352-11eb-82c2-45eeef31ca4a.png)

2. Create a response and access the field in the Text / Speech.

![image](https://user-images.githubusercontent.com/75699913/122985413-01bf6980-d353-11eb-9300-eef6c3252fa7.png)

3. Start a conversation with the bot

## Expected behavior
The field from the property is accessed and the message shows correctly.
Actual: No message is sent.

![image](https://user-images.githubusercontent.com/75699913/122985713-5bc02f00-d353-11eb-9d1b-c3f3788a1290.png)

## Additional context
We have stored Voices in a dictionary with key being the locale code and value being the voice object. We plan on passing these voices through the conversation update "ChannelData" field.

Curious if there is another way to express a field with a dash.

**Comment by boydc2014** [comment] 2021-07-14 10:37
Hi @bewillet, @dmvtech , this is somehow by designed that when you have a "-" in property name, you will have to use [] notion to access that property, otherwise, it will be undistinguishable from the "minus" operation.  For example, a.b-c has to be a["b-c"].

Can you try that see if it works?

**Comment by dmvtech** [comment] 2021-07-16 16:46
Hi @boydc2014 

Yes, that worked. 

Where this fails:
`Voices.en-US.d365_oc_ivrvoicename`

This succeeds:
`Voices["en-US"].d365_oc_ivrvoicename`

![image](https://user-images.githubusercontent.com/43397658/125981587-8fc793fc-b5d3-4077-9bf3-c9544734100a.png)

**Comment by mrivera-ms** [comment] 2021-07-19 16:51
Closing this issue as resolved. @bewillet, if you are still experiencing problems with this issue, please feel free to re-open it.

**Closed by mrivera-ms** 2021-07-19 16:51 UTC
Labels: Bot Services, bug, customer-replied-to, customer-reported, needs-triage
