### ISSUE TITLE
DCR: Add Slot property to Prompt class

### ISSUE THREAD

**Issue by tomlm** [microsoft/botframework-sdk#5091] opened 2018-10-02 17:56 UTC
## Issue
Currently prompt classes require the caller to take the output of a prompt and assign it to a slot.  This causes the following:
* on a waterfall, the next step needs to collect the slot value and save it
* it pushes a code requirement into the consumption of the Prompt.

## Proposed change
If we change the prompt class to have a property called "Slot" it can be configured to automatically "fill the slot" without requiring code behind.

## Component Impact 
Base prompt class in each SDK

## Customer Impact 
Should be additive, if the property is set people can start using it.

## Tracking Status
**Dotnet SDK**
- [ ] PR
- [ ] Merged

**Javascript SDK**
- [ ] PR
- [ ] Merged

**Samples**
- [ ] PR
- [ ] Merged

**Docs**
- [ ] PR
- [ ] Merged

**Java SDK** - n/a Dialogs library doesn't exist on java yet.
**Python SDK** - n/a Dialogs library doesn't exist on python yet.

[dcr]

**Comment by Stevenic** [comment] 2018-10-02 18:37
The issue is, the Prompt doesn't have access to the memory where the value needs to be stored.  Each dialog has its own isolated storage which it uses to accumulate values returned by calling prompts or other dialogs.  I haven't figured out a good workaround for this as everything I've thought of either violates the underlying stack model or comes with its own side effects.

**Comment by tomlm** [comment] 2018-10-02 20:13
I think we would have to create something like this:
```cs
class DialogSlotResult : DialogResult
{ 
     public string Slot 
    public object Result
}
```

**Comment by gabog** [comment] 2020-08-13 15:50
I think this issue is pretty old now and does not apply to the current state of the SDK, closing.

**Closed by gabog** 2020-08-13 15:50 UTC
Labels: BF Unknown, feature-request, needs-triage
