### ISSUE TITLE
Bot Channel Registration not showing up on dev.botframework.com

### ISSUE THREAD

**Issue by jonathanwagnerjambit** [microsoft/botframework-sdk#6288] opened 2021-05-11 17:03 UTC
## Version
4.11

## Describe the bug
My active "Bot Channel Registration" not showing up on dev.botframework.com page for unknown reasons.

## To Reproduce
Steps i did:
1. Go to dev.botframework.com
2. Click on "My Bots"
3. register new bot channel registration
4. after success go back to "My Bots"
5. see: "You don't have any bots or skills yet. Build a bot using the Bot Builder SDK and optionally provision your bot in Microsoft Azure."

## Expected behavior
see my bot registration

**Comment by tdurnford** [comment] 2021-05-12 18:02
@Andrea-Orimoto Can you take a look at this or route it to whoever you think is appropriate.

**Comment by Andrea-Orimoto** [comment] 2021-05-14 17:03
@jonathanwagnerjambit I can repro the issue, we'll take a look.

btw, I'm assuming you created the bot channel registration in the Azure Portal, If you stay in the Azure Portal and visit the Bot Services page, you should see all your bots in there https://portal.azure.com/#blade/HubsExtension/BrowseResource/resourceType/Microsoft.BotService%2FbotServices, which is the Azure equivalent of the My Bots page. Let me know if can find your bot there.

Thanks and sorry for the inconvenience.
Andrea

**Comment by Andrea-Orimoto** [comment] 2021-05-14 18:09
@jonathanwagnerjambit after checking with the team, this is by design, all Azure bots will not show up in the dev portal, please find them in the Azure portal at the link in the previous comment. We'll fix that page to make it clear. Thanks for reporting this, it is indeed confusing. I'm closing the isssue, feel free to reopen if you still have questions or concerns.

**Closed by Andrea-Orimoto** 2021-05-14 18:09 UTC
Labels: Bot Services, bug, customer-reported, needs-triage

**Comment by jcbartle** [comment] 2021-11-30 14:14
Morning, @Andrea-Orimoto. This behavior is still occurring within dev.botframework.com. It's definitely confusing, as I was trying to track down an issue I was having by looking at the Teams app schema here:

https://developer.microsoft.com/en-us/json-schemas/teams/v1.5/MicrosoftTeams.schema.json

This schema includes this comment regarding the botId attribute:

"The Microsoft App ID specified for the bot in the Bot Framework portal (https://dev.botframework.com/bots)"

But then I got there and started wondering if there was a larger issue with the Bot Framework since nothing was appearing. Glad I found this post so I didn't keep going down the wrong path.

@jonathanwagnerjambit - I do think this issue should be reopened while Microsoft sorts out where the "source of truth" regarding bots will be located and updating all related documentation. That's just my opinion, though. Thanks for opening the original issue - definitely saved me some time!
