### ISSUE TITLE
Unable to call bot service when we've enabled NGNIX & Fortigate for appservice in azure portal

### ISSUE THREAD

**Issue by samthrusha123** [microsoft/botframework-sdk#6624] opened 2023-12-04 05:53 UTC
All the bot services I created in azure portal are working fine until we add ngnix & fortigate to appservices. After that it's not even responding.

Getting the below error when tries in web chat

{ "error": { "code": "BotError", "message": "Failed to send activity: bot returned an error" } }

can you please specify what the issue is?

**Comment by stevkan** [comment] 2023-12-04 22:38
Closing as duplicate of Botbuilder-Samples issue, #[3930](https://github.com/microsoft/BotBuilder-Samples/issues/3930).

**Closed by stevkan** 2023-12-04 22:38 UTC
Labels: bug, needs-triage
