### ISSUE TITLE
CHATBOT ONSCREEN KEYBOARD UNSUPPORTED

### ISSUE THREAD

**Issue by caleberi** [microsoft/botframework-sdk#6160] opened 2021-01-12 12:53 UTC
Intergrating an html/css/js onscreen keyboard with a csharp version of  bot  seems impossible . why ?

**Comment by jwiley84** [comment] 2021-01-12 17:00
Closing as a duplicate of https://github.com/microsoft/BotFramework-WebChat/issues/3662

**Closed by jwiley84** 2021-01-12 17:00 UTC
Labels: bug, needs-triage
