### ISSUE TITLE
Recognizer dependency needs acceptance testing

### ISSUE THREAD

**Issue by johnataylor** [microsoft/botframework-sdk#5337] opened 2018-09-19 16:35 UTC
We have had a few problems with the Recognizer packages breaking our scenarios. We have had not just individual features broken but also broken builds. 

We should consider the development of a set of tests that accurately characterize this critical dependency.

Currently we have locked the dependency to a specific version because the open version dependency has caused our build to break.

If we want to revert to open dependency (allowing automatic upgrade of minor and patch) we should first develop a process with the Recognizer team such that the packages are tested for compatibility before publication.

**Comment by cleemullins** [comment] 2019-06-20 22:25
@EricDahlvang is working on this now.

**Comment by cleemullins** [comment] 2019-09-19 23:16
We've made headway in C#, and are currently looking at this in JS.

**Comment by EricDahlvang** [comment] 2019-11-12 21:15
I've been using the following code to test recognizer library changes in dotnet:
[BotBuilderPrompts-Recognizers-Tests.zip](https://github.com/microsoft/botframework-sdk/files/3838229/BotBuilderPrompts-Recognizers-Tests.zip)

Run it once while referencing one version of the recognizer's libraries in Microsoft.Bot.Builder.Dialogs, to create baseline files.  Run it a 2nd time against different versions of recognizer's libraries and it will do a comparison of results and write differences to _Error.txt files.

Guidelines I've been using to determine if something is a breaking change, new feature or regression:

-----

As a dependency, the Recognizers have the potential to drastically change a bot’s behavior.  Developers consuming the Bot Builder SDK have the expectation that minor and patch version changes will be backward compatible.
 
Based on semver rules:

*Given a version number MAJOR.MINOR.PATCH, increment the:

1. MAJOR version when you make incompatible API changes,
2. MINOR version when you add functionality in a backwards compatible manner, and
3. PATCH version when you make backwards compatible bug fixes.

Recognizer changes can be considered either:

1) A backwards incompatible change requiring Bot Builder MAJOR version change.  
      - Example: expected results must continue to be returned from methods exposed by the SDK libraries, which includes the Prompts and ChoiceRecognizers.
                                Prompt: NumberPrompt
                                Utterance: $500
                                v1.1.3: [{"Succeeded":true,"Value":500}]
                                v1.2.6.1: [{"Succeeded":false,"Value":0}]

      - '$500' was recognized by the NumberModel with a value of 500, but now is not.  This is an example of an incompatible and breaking change, which would require upgrading the Bot Builder MAJOR version number.

2) A backwards compatible new feature, allowed in MINOR versions
      - Example: correct results are returned where nothing was previously returned.  
                                Prompt: DateTimePrompt 
                                Utterance: halloween
                                v1.1.3: null
                                v1.2.6: [{"Succeeded":true,"Value":[{"Value":"1999-10-31","Start":null,"End":null,"Timex":"XXXX-10-31"},{"Value":"2000-10-31","Start":null,"End":null,"Timex":"XXXX-10-31"}]}]

3) A backwards compatible bug fix, allowed in PATCH versions 
      - Example: something was previously recognized as a mistaken value, or not recognized at all.
                                Prompt: DoublePrompt
                                Utterance: half
                                v1.1.3: [{"Succeeded":false,"Value":0.0}]
                                v1.2.6: [{"Succeeded":true,"Value":0.5}]

      - 'half' is now correctly recognized as .5, while before it was not.  This is an example of a bug fix and PATCH

*reference: 
Semantic Versioning 2.0.0
https://semver.org/

**Comment by EricDahlvang** [comment] 2019-11-22 19:23
Closing this, since we have a manual 'acceptance testing' plan (see above).  We certainly could make this more automated, but the nature of the issue itself does seem to require a level of human acceptance or rejection of results.

**Closed by EricDahlvang** 2019-11-22 19:23 UTC
Labels: R7
