### ISSUE TITLE
send_activity hangs sometimes

### ISSUE THREAD

**Issue by maramizo** [microsoft/botframework-sdk#6460] opened 2022-01-28 22:11 UTC
## Version
4.14.1

## Describe the bug
Sending text activity through turn_context.send_activity sometimes freezes the thread entirely.

## To Reproduce
The following snippet shows an example:
```py
    async def on_message_activity(self, turn_context: TurnContext):
        if turn_context.activity.attachments:
            invalid_attachments = 0
            for attachment in turn_context.activity.attachments:
                if not (attachment.name and any(x in attachment.content['fileType'] for x in
                                                ['xlsx', 'xlsb', 'csv', 'xlsm'])):
                    if attachment.content_type != 'text/html':
                        invalid_attachments += 1
                    continue
                try:
                    # From this point on, this code is simply to show some of the processing that happens in the background 
                    # until the next annotation, where the actual issue occurs. This code takes about a minute or two to process.
                    ###############################################################################
                    if 'csv' in attachment.name:
                        file = pd.read_csv(attachment.content['downloadUrl'])
                    else:
                        file = pd.read_excel(attachment.content['downloadUrl'])
                    print("Sending file received.")
                    await self.persistent_message("File received, processing.", turn_context)
                    result = handler.handle_file(file)
                    if result[0] == 1 and handler.file_type:
                        user_name = turn_context.activity.from_property.name
                        month_day = datetime.now().strftime("%m %d")
                        path = f"{DefaultConfig.ONEDRIVE_FOLDER}\\Uploads\\{user_name}\\{handler.file_type}\\{month_day}"
                        print(path)
                        Path(path).mkdir(parents=True, exist_ok=True)
                        files = os.listdir(path)
                        max_index = 0
                        if len(files):
                            files = [x.replace(". Upload.csv", "") for x in files]
                            files = [int(x) for x in files]
                            max_index = max(files)
                        file_name = f"{max_index + 1}. Upload.csv"
                        result[2].to_csv(f"{path}\\{file_name}")
                        result[1] = "Your file has been saved at: **Uploads/%s/%s/%s/%s**.   \n\n%s" % (
                            user_name, handler.file_type, month_day, file_name,
                            result[1]
                        )

                    ###############################################################################
                    # THIS IS THE MAIN ISSUE/BUG:
                    ###############################################################################
                    # This print always shows the correct message to be sent.
                    print(f"Sending message {result[1]}")
                    message = MessageFactory.text(result[1])
                    message.text_format = TextFormatTypes.markdown

                    # This send_activity hangs sometimes.
                    await turn_context.send_activity(message)

                    # When the previous send_activity hangs, this print never displays.
                    print("Message sent.")
                except Exception as e:
                    print(e)
                    await turn_context.send_activity(f"Invalid file content, file is possibly corrupted.\n"
                                                     f"Please ensure the file format is .xlsx, .xlsb or .csv.")
            if invalid_attachments > 0:
                await turn_context.send_activity(f"{invalid_attachments} invalid attachment(s) sent. "
                                                 f"Please only send .csv, .xlsx or .xlsb files.")
```

## Expected behavior
The annotated send_activity should always send properly, or at least not hang the thread.

## Screenshots
![image](https://user-images.githubusercontent.com/7774220/157925223-d4f0a186-ce06-4b36-8d83-2887bdead151.png)

## Additional context
This bot is hosted on an EC2 instance on Amazon.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by dmvtech** [comment] 2022-01-31 22:07
hi @maramizo 

Are you able to isolate further at all? Does this reproduce with a locally running bot with Emulator? Or without sending attachments to Onedrive? Does it only reproduce in the Teams channel?

> This code takes about a minute or two to process

Regarding this, you should use proactive messages when dealing with long running operations (over 15 seconds). Although not every channels is the same, it's still a best practice.

https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-long-operations-guidance?view=azure-bot-service-4.0

**Comment by maramizo** [comment] 2022-02-01 12:29
I was able to close up on the root issue being somewhere in msrest send functions, between two different classes which I don't currently recall. It seems that one of the request builders hang the thread as they never receive a response. I'm not sure why task.cancel() doesn't immediately cancel the request building process though.

The issue does not reproduce locally from my tests but it's tough to reproduce in the first place because there's no specific steps to reproduce, it just sometimes fails to send.

It happens in a conversation channel, not a teams channel. Haven't tested it without sending files to the OneDrive folder.

I figured I'd have to approach this by using proactive messages (even though the context is just a 1:1 conversation).

**Comment by maramizo** [comment] 2022-02-07 16:50
Using proactive messages no longer causes this issue - must be something with using the existing turn activity after a while.

**Comment by dmvtech** [comment] 2022-02-07 23:03
Thank you for the update and info. 

As you've got a better solution and we can't easily reproduce, I'll go ahead and close this one. If you find more info, or a more consistent repro, please comment.

**Comment by maramizo** [comment] 2022-03-06 08:15
Re-opening this. Even when forging a new context to send a message, this issue still occurs.

Issue is confirmed to only occur when moving a file into a OneDrive folder before sending the message.

**Comment by maramizo** [comment] 2022-03-07 14:10
What's funny is that if you reverse the order, so that it sends the message then saves the file, it refuses to save the file as well. My guess is that there's some sort of underlying authentication method that prevents two different endpoints from acting upon msrest? Not sure.

**Comment by dmvtech** [comment] 2022-03-10 17:08
@clearab Would you have any insight here? Are there additional steps that need to be taken?

**Comment by clearab** [comment] 2022-03-11 19:44
I'm not sure how either Teams or the SDK could really be involved in this - the code for send activity is really straightforward (it just makes the http call), and Teams APIs aren't really involved in any of this. A threading bug in an underlying dependency maybe? @tracyboehrer  any ideas?

**Comment by tdurnford** [comment] 2022-04-11 13:51
@axelsrz Have you been able to take a look at this?

**Comment by msomanathan** [comment] 2022-04-25 17:57
@axelsrz Could you please provide updates on this issue? Thanks!

**Comment by axelsrz** [comment] 2022-05-06 20:08
Will try to repro this soon, but this might be related to something external to the sdk

**Comment by ramfattah** [comment] 2022-05-20 20:14
Hi @maramizo 

I was not able to reproduce. 
Sending text activity with `turn_context.send_activity` works as expected using [15.handling-attachments/](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/python/15.handling-attachments) sample.

#

> Issue is confirmed to only occur when moving a file into a OneDrive folder before sending the message.

Are you able to share a minimal reproducible zipped bot project?


Thanks.

**Comment by ramfattah** [comment] 2022-05-31 18:08
Closing due to inactivity, @maramizo please feel free to re-open if needed.

**Closed by ramfattah** 2022-05-31 18:08 UTC
Labels: bug, customer-replied-to, customer-reported, Bot Services, needs-triage
