### ISSUE TITLE
Teams Bot messages dont show up - notification appears though

### ISSUE THREAD

**Issue by sridhar21111976** [microsoft/botframework-sdk#5624] opened 2019-09-19 07:12 UTC
## This is not for asking questions or filing bugs

I have an issue where the teams Bot reply shows up in the notification, but not in the message window. A close and open of teams shows the message... So no issue in the actual message delivery itself. Something to do with how teams handles the new message..... Same behavior in Teams web too...

tried redeploying the channel in Azure bot service - still the same behavior....

**Comment by CezaryMarcjan** [comment] 2019-09-19 17:02
@sridhar21111976 thanks for the report. We'll investigate.

**Comment by tsuwandy** [comment] 2019-09-20 03:12
@wajeed-msft, could you take a look at this issue and see if it’s a bug?  Thanks!

**Comment by Wajeed-msft** [comment] 2019-09-23 03:59
@sridhar21111976- Is this happening with other Bots as well? Is anyone else in your team facing the same issue?

**Comment by sridhar21111976** [comment] 2019-09-23 08:03
Hi Wajeed,  I have only one bot deployed. The issue was with all Teams interface outside the web test interface.
Interestingly the issue resolved on its own. It’s working fine right now. Not sure if this is due to the publishing the app to groups and channels as against as a personal chat interface..

**Comment by carlosscastro** [comment] 2019-09-23 18:07
@sridhar21111976 It sounds like the issue is resolved. Can you please confirm? Thanks

**Comment by sridhar21111976** [comment] 2019-09-24 00:27
Hi Carlos, Yes.. so far it’s working ok... does the initial problem attribute to any wait time for the service to be prepared in the backend .. or should that be working straight from the time of creation and expose through the channel...! Would you know..?

Rest is all good consider the case closed as it’s working now.. I will post back here based on my next bot, when I create one...

**Comment by stevengum** [comment] 2019-10-01 06:28
@sridhar21111976 since the issue was resolved I'm going to close this issue. Thanks for confirming that the bug resolved itself.

@Wajeed-msft can you comment on the question from @sridhar21111976?

> ... does the initial problem attribute to any wait time for the service to be prepared in the backend .. or should that be working straight from the time of creation and expose through the channel...!

**Closed by stevengum** 2019-10-01 06:28 UTC
Labels: Bot Services, customer-replied-to, customer-reported
