### ISSUE TITLE
Bot in Teams channel not responding well.

### ISSUE THREAD

**Issue by ivikashjha** [microsoft/botframework-sdk#5633] opened 2019-10-01 05:54 UTC
My Bot is added under Teams tab of Microsoft Teams Channel. When i start a conversation and I stay in same chat thread, I am not using any mouse click, then in that case Bot name does not appear with @BotName , when i click outside or on bot response notification the Reply link appear just below the response. For our day to day user, most of them are not technical people, how can we make sure the Bot is responding correct.
![MicrosoftTeamsGitHub](https://user-images.githubusercontent.com/2158150/65937608-0a189800-e43e-11e9-96b7-1e186e118a66.png)

**Comment by ivikashjha** [comment] 2019-10-01 05:57
![PurpleReply](https://user-images.githubusercontent.com/2158150/65937664-38967300-e43e-11e9-9f99-5a2df023b627.png)

Purple reply link displays @BotName that make sures bot is listening. But Reply text otherwise does not goes to Bot and it just stays there forever without any response from Bot. How to resolve this issue. Is this something we can fix or use some work around, or we need to look for other channel other than Microsoft Teams.

**Comment by mdrichardson** [comment] 2019-10-01 17:25
Closing as this is a duplicate of https://github.com/microsoft/BotBuilder-Samples/issues/1787 and the other is in a more appropriate repo for bug reports.

@ivikashjha If you don't believe this is a duplicate, let me know. Otherwise, we'll use that thread for supporting this issue.

**Closed by mdrichardson** 2019-10-01 17:25 UTC
Labels: Bot Services, customer-reported, teams
