### ISSUE TITLE
404 not found when testing the AADv2 Auth Sample 

### ISSUE THREAD

**Issue by muhualing** [microsoft/botframework-sdk#5464] opened 2019-07-15 05:13 UTC
when I tested the [auth bot sample](
https://github.com/microsoft/BotBuilder-V3/blob/54bc8e6fa9b1582742beebeaa4d7254b39421639/Node/examples/basics-oauth/app.js#L32-L104), I met 404not found error

SDK Platform: Nodejs
SDK Version: 3.16.0
Active Channels: Teams
Deployment Environment: Azure Bot Service

Error: GET to 'https://api.botframework.com/api/usertoken/GetToken?userId=29%3A1R5vQA_0_OF8C4zi2Sy5uQs77pFKXs6Jxx1-UW7fABq7XqkNQ_CrL-lstObXd3RL6MVj_UZIC1PQ3fZGh-YdNFA&connectionName=ConnectionNameV2' failed: [404] Not Found

mycode:

```python
connector.getUserToken(session.message.address, connectionName, undefined, (err, result) => {
    if (result) {
        // If there is already a token, the bot can use it directly
        session.send('You are already signed in with token: ' + result.token);
    } else {
        // If there not is already a token, the bot can send an OAuthCard to have the user log in
        if (!session.userData.activeSignIn) {
            session.send("Hello! Let's get you signed in!");
            builder.OAuthCard.create(connector, session, connectionName, "Please sign in", "Sign in", (createSignInErr, signInMessage) =>
            {
                if (signInMessage) {
                    session.send(signInMessage);
                    session.userData.activeSignIn = true;
                } else {
                    session.send("Something went wrong trying to sign you in.");
                }     
            });
        } else {
            // Some clients require a 6 digit code validation so we can check that here
            session.send("Let's see if that code works...");
            connector.getUserToken(session.message.address, connectionName, session.message.text, (err2, tokenResponse) => {
                if (tokenResponse) {
                    session.send('It worked! You are now signed in with token: ' + tokenResponse.token);
                    session.userData.activeSignIn = false;
                } else {
                    session.send("Hmm, that code wasn't right");
                }
            });
        }
    }
});
```

The Client id in the OAuth connection is my bot's AppId, the Client secret is my bot's password, and the Tenant ID is the bot's domain.
The connection name is also right(the one in Azure)
![image](https://user-images.githubusercontent.com/12086605/61196457-55ee5780-a701-11e9-9db5-bc8229c1cd3d.png)

**Comment by jwiley84** [comment] 2019-07-18 19:05
That is a older sample. Let me see if I can figure out what's going on

**Comment by jwiley84** [comment] 2019-07-18 19:10
Have you tested your connection in the app portal?

![image](https://user-images.githubusercontent.com/17333688/61485012-fab4a300-a954-11e9-9e3c-4e79a6f16b8c.png)

**Comment by muhualing** [comment] 2019-07-20 01:38
> Have you tested your connection in the app portal?
> 
> ![image](https://user-images.githubusercontent.com/17333688/61485012-fab4a300-a954-11e9-9e3c-4e79a6f16b8c.png)

Sure, I tested it and I can get a token.

**Comment by jwiley84** [comment] 2019-07-22 16:35
Good! It means your OAuth is set up right. Investigating!

**Comment by jwiley84** [comment] 2019-07-22 16:38
Just to toss it out there: I believe the issue is the channel. Teams takes some special handling. Can you test your oauth in another channel?

**Comment by CoHealer** [comment] 2019-07-29 20:53
@muhualing , can you please acknowledge? Otherwise we'll have to close the issue.Thanks.

**Comment by sgellock** [comment] 2019-08-01 16:05
should this live in the samples repo?

**Comment by jwiley84** [comment] 2019-08-01 19:52
This belongs in either v3 or sevices repo.

**Comment by CoHealer** [comment] 2019-08-05 16:45
@muhualing I'm closing this for lack of response. If you still need assistance please re-open.

**Closed by CoHealer** 2019-08-05 16:45 UTC
Labels: Support, customer-replied-to, customer-reported
