### ISSUE TITLE
Return to application without granting consent displays Error Message

### ISSUE THREAD

**Issue by ManuNswamy** [microsoft/botframework-sdk#6137] opened 2020-12-08 13:24 UTC
Post the sign in, a page which prompts consent for the permissions needed for the application is displayed. On selecting "return to the application without granting consent" option an error message is displayed[screenshot attached].

![image](https://user-images.githubusercontent.com/29920276/101489316-ca750680-3986-11eb-8905-297465522c8d.png)

I have followed the page by microsoft that is https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=aadv2%2Ccsharp and did the configuration in our bot with redirect URI as https://token.botframework.com/.auth/web/redirect. We are using the OauthPrompt to sign in the user in our MS Teams bot application.
 
If anybody has any resolution for the issue, then please let me know.  Thanks in Advance

**Comment by jwiley84** [comment] 2020-12-08 19:24
Hi @ManuNswamy 

Thank you for bringing this to our attention. I'm going  to attempt a repro of this issue: in the meantime, can I get a few more details: 
Are you using any of our samples as the base for this bot, such as the [Sample 18. Bot Authentication]() or [Sample ## Authentication with MSGraph]()? 
Which language SDK are you using? 
Are you using AADv1 or AADv2?

Thank you!

**Comment by ManuNswamy** [comment] 2020-12-09 13:35
We are not using any of the samples. Our application is built using C# with AADv2,

**Comment by anusharavindrar** [comment] 2020-12-11 21:19
Looking into this. Will attempt a repro on my end and update the thread.

**Comment by anusharavindrar** [comment] 2020-12-21 03:28
@ManuNswamy, apologize for the delay in response. I am unable to repro the issue on my end. As soon as I connect to the Teams channel and sign in, it does not open the page which prompts consent for the permissions needed for the application is displayed, but just logs me in with an option to view the token. Could you elaborate on the steps that led you to getting the ServiceError? 
![image](https://user-images.githubusercontent.com/48731427/102735258-c9cd6000-42f6-11eb-97c5-0157b799eeee.png)

**Comment by anusharavindrar** [comment] 2020-12-28 23:14
Closing due to no response. Please feel free to re-open if issue persists.

**Comment by ManuNswamy** [comment] 2021-01-11 10:05
Hi Team,

My sincere apologies for not responding to the thread.

The scope used in azure connection string AADv2 is **openid profile email User.Read Group.Read.All ChannelMessage.Send**  

To get a prompt for consent window, you will have to add the scope as mentioned above. Do let me know if there is any more information needed.

**Comment by anusharavindrar** [comment] 2021-01-22 17:42
@ManuNswamy, thanks for the additional information above. Let me repro the issue with the above scopes and get back with my findings.

**Comment by anusharavindrar** [comment] 2021-01-27 00:13
@ManuNswamy, here are my repro steps:

-   As soon as I connect to the Teams channel, I get this:
![image](https://user-images.githubusercontent.com/48731427/105919927-13971d80-5ffc-11eb-9e2d-e02ee1c5f443.png)

- When I click on 'Sign in', it prompts me to the Microsoft Sign In page and post the sign in, I get this page asking for permissions:

![image](https://user-images.githubusercontent.com/48731427/105920148-77214b00-5ffc-11eb-9979-d09a94549480.png)


- I am still not able to get the "return to the application without granting consent" option . Only when I click on the **No** option, I get the ServiceError.

![image](https://user-images.githubusercontent.com/48731427/105923186-9a022e00-6001-11eb-86cb-25ae206faf14.png)

- This is the scope of my AADv2 OAuth Connection settings on Azure, '**openid profile email User.Read Group.Read.All ChannelMessage.Send'**
![image](https://user-images.githubusercontent.com/48731427/105923339-d7ff5200-6001-11eb-95c2-335b46665325.png)

Please let me know if I am missing on any steps.

**Comment by ManuNswamy** [comment] 2021-01-28 09:32
Thank you reproducing the scenario. I see that you were able to get the ServiceError which is the similar error to what we were getting during the sign in, so could you please provide us any details that you possibly resolve the issue ?

To get the "Return to application without granting consent" option, could you please try to login using a general user without any specific roles or permissions [Atleast roles should not be Global Administrator, Application Administrator, or  Cloud Application Administrator]? 

Attaching the screenshot of the consent window that we see during the sign in

![Approve](https://user-images.githubusercontent.com/29920276/106118186-d8225d80-6179-11eb-84d9-56dae1b4a6fe.png)

**Comment by ManuNswamy** [comment] 2021-02-03 16:52
@anusharavindrar 
Were you able to repro the scenario. Any resolution step to have the Service Error fixed?

Thanks in Advance !

**Comment by anusharavindrar** [comment] 2021-02-05 00:34
@ManuNswamy, currently investigating this further. Will update the thread as soon as I have some more info to share. Thanks for your patience.

**Comment by anusharavindrar** [comment] 2021-02-11 18:14
@ManuNswamy, I was able to repro the scenario and got the ServiceError. I am currently working internally to get more information on the ServiceError and the expected behavior.

**Comment by congysu** [comment] 2021-02-22 23:36
@anusharavindrar can you please flag a Milestone for this issue?  Thanks.

**Comment by anusharavindrar** [comment] 2021-02-23 01:38
@ManuNswamy, so if you want the consent to work, then you need to figure out the the admin consent part about your tenant and try out these 3 options – 
1)	The end user is an admin in the tenant, and can click the “Have an admin account” link below and grant consent.
2)	A global admin provides consent at the app level for all users in the tenant - https://docs.microsoft.com/en-us/azure/active-directory/manage-apps/grant-admin-consent#:~:text=Grant%20admin%20consent%20in%20App%20registrations&text=Select%20Azure%20Active%20Directory%20then%20App%20registrations.,the%20permissions%20the%20application%20requires.
3)	Remove the scopes that need admin consent.
 
For the second part, which is the ServiceError you get when you select “**return to the application without granting consent**”, it would be a feature work that needs to be planned and completed based on the priority of our team. I will link the feature work item here once its created and you can track the progress of the work item.

**Comment by ManuNswamy** [comment] 2021-02-25 04:15
Thanks Team for reproducing the issue and considering it as a feature work.

**Comment by daveta** [comment] 2021-03-12 20:47
Hi @ManuNswamy : I'm closing this primary issue - we can follow progress in the linked issue.
Thanks for reporting the issue!

**Closed by daveta** 2021-03-12 20:47 UTC
Labels: Bot Services, customer-replied-to, customer-reported
