### ISSUE TITLE
Adaptive Dialog called through code which calls a skill produces the error: System.NullReferenceException: 'Unable to locate SkillConversationIdFactoryBase in HostContext'

### ISSUE THREAD

**Issue by silverbulletgt** [microsoft/botframework-sdk#6143] opened 2020-12-17 14:57 UTC
## Version
4.11.1

## Describe the bug
After following the instructions on this post: experimental-add-composer I get the error System.NullReferenceException: 'Unable to locate SkillConversationIdFactoryBase in HostContext' when using an trigger intent which calls a skill as part of its conversation flow.

## To Reproduce
I have created a git repo to demonstrate the issue as there are many steps to reproduce.
[git repo with project that demonstrates the issue](https://github.com/silverbulletgt/Integrate-Composer-Dialog-Using-Skill)

To recreate the issue:
Prerequisites
Install Bot Emulator: [Emulator project link](https://github.com/Microsoft/BotFramework-Emulator/blob/master/README.md)
 
Open the solution file
Integrate-Composer-Dialog-Using-Skill.sln
 
Put a breakpoint on line 72 of DefaultAdapter.cs - this is where the error can be seen
 
Start debugging the project
Open Bot Emulator
Connect to the bot: http://localhost:3978/api/messages
Type "Greeting"
Bot should respond with "Hello, I have recognized that you said greeting"
Type "Skill"
The breakpoint on line 72 of DefaultAdapter.cs should trigger giving details of the error

Error & stack trace can be found here: [Stack Trace](https://github.com/silverbulletgt/Integrate-Composer-Dialog-Using-Skill/blob/master/Readme/error%20stack%20trace.txt)

## Expected behavior
The skill would be called successfully

## Screenshots
[error stack trace.txt](https://github.com/microsoft/botframework-solutions/files/5705970/error.stack.trace.txt)
The process I followed to setup the project to produce the error.
[Detailed Instructions.docx](https://github.com/microsoft/botframework-solutions/files/5705971/Detailed.Instructions.docx)

## Additional context
The goal of setting this up is to create a workflow which allows composer created dialogs to be integrated into a bot skill project.
This will allow for customizations to the bot behavior such as, logging errors & conversation to a custom database hosted on premise.
We will also be hosting the bot on premise so this structure will also allow for our CI/CD pipeline to deploy the main bot (created through the composer) & skills (created in code) to be deployed together & settings to be adjusted as the Bot moves up environments.

Thank you for your time in reviewing this issue.

## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by v-kydela** [comment] 2020-12-17 19:09
Closing as duplicate of https://github.com/microsoft/botbuilder-dotnet/issues/5057

**Closed by v-kydela** 2020-12-17 19:09 UTC
Labels: Bot Services, bug, customer-reported, needs-triage
