### ISSUE TITLE
Node module “open” is not opening URL

### ISSUE THREAD

**Issue by sanjeevgaut** [microsoft/botframework-sdk#5616] opened 2019-09-15 10:30 UTC
I am trying to open URL using node module OPEN, but it is not working. I have installed Open and i can see the open module in node module folder.

Below is my code.

const open = require('open');

open('https://myurl');

I am working on Microsoft bot framework. Deployed the code in AZURE. The same code is working in emulator but in browser it is not working.

Any help is appreciated.

Thanks Sanjeev Gautam

**Comment by tdurnford** [comment] 2019-09-15 16:04
Closing as this seems to be a duplicate of this [question](https://stackoverflow.com/questions/57943209/node-module-open-is-not-opening-url) on StackOverflow. 

The Open npm package is trying to open the target in the default app for the file type. For example, URLs open in your default browser.  Since you are using this package in your bot, it is trying to open the browser in Azure - not on the users machine.

**Closed by tdurnford** 2019-09-15 16:04 UTC
