### ISSUE TITLE
bot not doesnt work after deployement on azure with orchestrator

### ISSUE THREAD

**Issue by pramodphamax** [microsoft/botframework-sdk#6462] opened 2022-02-10 16:02 UTC
## Version
What package version of the SDK are you using.

## Describe the bug
Give a clear and concise description of what the bug is.

## Expected behavior
using the code here https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/javascript_nodejs/14.nlp-with-orchestrator

The code works on the local but, when deployed to azure using steps here -> https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=javascript%2Cmultitenant

The deployemnt is successful, but bot throws and error

## Screenshots
![Orchestrator](https://user-images.githubusercontent.com/87850728/153445751-41c484d5-c063-4a05-a509-c7067a31924d.PNG)
## Tracking Status

**Dotnet SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Javascript SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Python SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Java SDK** [TODO]()
- [ ] PR
- [ ] Merged

**Samples** [TODO]()
- [ ] PR
- [ ] Merged

**Docs** [TODO]()
- [ ] PR
- [ ] Merged

**Tools** [TODO]()
- [ ] PR
- [ ] Merged

**Comment by dmvtech** [comment] 2022-03-03 05:27
I can reproduce this. Still investigating potential causes.

**Comment by dmvtech** [comment] 2022-03-03 19:12
Hi @daveta Can you take a look at this and see what you can find?

**Comment by daveta** [comment] 2022-03-03 19:18
Hi @pramodphamax : 
Can you provide some info on how you provisioned?  Orchestrator models take a fair amount of memory, it's best to run on a 64-bit VM?

**Comment by hcyang** [comment] 2022-03-17 06:21
Hi, we are able to reproduce the bug. The situation is that we also built the Orchestrator bot in a x64 Windows environment, so 'npm install' would download some Orchestrator native libraries in x64 format. These native libraries were then (manually) zipped up with the rest of bot files and deployed to a standard-tier Azure service (S1). Unfortunately, this standard-tier Azure service is default to run on an x86 VM, so the deployed bot would throw the not-a-win32-application error while loading a x64 binary. This error cannot be easily fixed by simply reconfiguring and restarting the service to x64, even though both x86 and x64 NODEJS were installed in the VM, as the **original PATH setting gives the x86 node.exe the priority**. 
The deployment guide (https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-deploy-az-cli?view=azure-bot-service-4.0&tabs=multitenant%2Cnewgroup%2Cjavascript#prepare-your-project-files) **should have been clearer on the x86/x64 distinction. **

Here are some workarounds:
1) Use a x86 environment for building the bot and still deploy it to the standard-tier (S1) service.
2) Use a service plan that starts with a x64 VM.

![image](https://user-images.githubusercontent.com/370110/158748182-98748bcd-6a5d-45ae-b260-bce864f76309.png)

**Comment by munozemilio** [comment] 2022-04-04 18:09
Hello @pramodphamax. Im closing this due to inactivity. Feel free to reopen if needed

**Closed by munozemilio** 2022-04-04 18:09 UTC
Labels: bug, customer-replied-to, customer-reported, Bot Services
