### ISSUE TITLE
Custom Data error in Micrrosoft Bot Service

### ISSUE THREAD

**Issue by sachin07** [microsoft/botframework-sdk#5695] opened 2019-12-13 10:02 UTC
Hi All,

I am facing an issue while hitting the below url of Direct Line API:

https://directline.botframework.com/v3/directline/conversations/Conversationid/activities

Header i am passing :
 token

Body 

{
    "type": "message",
    "from": {
        "id": "user1"
    },
    "text": "hello"
}

but i am getting below error 

{
  "error": {
    "code": "MissingProperty",
    "message": "Missing 'Activity.From' field"
  }
}

Chatbot having custom parameters but not able to figured out how to pass the same.
Can anyone help me

I have to integrate my custom Microsoft bot with Android native.

Thanks,
Sachin

**Comment by jwiley84** [comment] 2019-12-13 16:05
Closing this as a duplicate of [here](https://stackoverflow.com/questions/59320293/custom-data-error-in-microsoft-bot-service)

**Closed by jwiley84** 2019-12-13 16:05 UTC
