### ISSUE TITLE
Bot Menu's Persist on Teams Client Even When Removed

### ISSUE THREAD

**Issue by don4of4** [microsoft/botframework-sdk#6101] opened 2020-11-09 17:49 UTC
## Version
4.10.3

## Describe the bug
**Once Bot menus are added to a bot package, they cannot be removed (at all).** If a subsequent update removes those menu's, they persist for all users.  Uninstalling and reinstalling the app does not resolve the issue, nor does client uninstall; making this a **major headache**.

Also observed below: if a totally new app is created which makes reference to a bot id (previously associated with a teams app  manifest which had a bot menu), the undeletable bot menu's will also persist on this otherwise virgin app, despite never having a bot menu.  This appears to infer that the bot menu is linked to the bot state in some way that is inappropriate (it should be associated to the app).

Basically bot menu's are an immutable virus that you can't get rid of without admin intervention to uninstall the retire app from the org and install a new one.  

## To Reproduce
1. Create a manifest that includes Bot menu's.
2. Install it on one or more users.
3. Change the manifest, and push an organizational update or uninstall and re-sideload (both result in the same issue)
4. You will see that the bot menus persist. 

## Expected behavior
If the manifest is updated to remove bot menu's I would expect the menu to disappear on subsequent updates.

## Screenshots
_Manifest has no menus:_
![image](https://user-images.githubusercontent.com/871843/98577303-5ceb9280-2281-11eb-8dce-c772c55d4e84.png)

_Menu appears:_
![image](https://user-images.githubusercontent.com/871843/98577319-6412a080-2281-11eb-98b7-48a6e0bf3acd.png)

**Comment by clearab** [comment] 2020-11-13 17:55
Removed Azure support tracking tags (as this is purely a Teams client issue) and sent to Teams support. I will follow up if no response from them by 11/17/2020.

**Comment by clearab** [comment] 2020-11-18 20:19
I've been unable to recreate this behavior - is this issue still persisting? Can you please let me know if a close/reopen of the Teams client results in the menu's being removed as expected? 

If the issue is still present, can you please let me know if you're altering the app ID (not the bot ID, but the app ID for the Teams app)?

**Comment by don4of4** [comment] 2020-11-18 23:25
@clearab I am able to repro this trivially. In fact -- I can even create a brand new Teams App, and **if I link it to the same BOT Guid, the menu is also there!**  It looks like teams is attaching the bot menu to the bot ID, then once that happens you can't change the manifest of the teams app to remove it.  It's actually being attached on the backend w/ the bot identifier?

Repro Steps:
1. Create an entirely fresh bot manifest
2. Attach to **App Id:** 47e5b779-9c03-4609-98c3-ff06cd7cc142
3. See menu

**Comment by don4of4** [comment] 2020-11-18 23:27
For the avoidance of doubt, take a look at this:
`{
  "$schema": "https://developer.microsoft.com/en-us/json-schemas/teams/v1.8/MicrosoftTeams.schema.json",
  "manifestVersion": "1.8",
  "version": "1.0.0",
  "id": "8935d11a-df54-4045-ab1b-cf6bd129f3af",
  "packageName": "com.test",
  "developer": {
    "name": "Hitachi Solutions (Don Scott)",
    "websiteUrl": "https://global.hitachi-solutions.com",
    "privacyUrl": "https://global.hitachi-solutions.com/j",
    "termsOfUseUrl": "https://global.hitachi-solutions.com/f"
  },
  "icons": {
    "color": "color.png",
    "outline": "outline.png"
  },
  "name": {
    "short": "TestApp",
    "full": "THis is a test"
  },
  "description": {
    "short": "This is a test",
    "full": "Testy test test."
  },
  "accentColor": "#FFFFFF",
  "bots": [
    {
      "botId": "47e5b779-9c03-4609-98c3-ff06cd7cc142",
      "scopes": [
        "personal"
      ],
      "commandLists": [
        {
          "scopes": [
            "personal"
          ],
          "commands": [
            {
              "title": "Test",
              "description": "test"
            }
          ]
        }
      ],
      "supportsFiles": false,
      "isNotificationOnly": false
    }
  ],
  "permissions": [
    "identity",
    "messageTeamMembers"
  ],
  "validDomains": []
}`

Yet I see:
![image](https://user-images.githubusercontent.com/871843/99600601-61235880-29c3-11eb-942b-3e8bc489093f.png)

**Comment by clearab** [comment] 2020-11-19 03:22
That's interesting, when I installed your app I got the single "test" command - which makes me think something is caching in your local client. Do you get the same menu if you open the app in the web browser or on mobile (trying to figure out where the cache is happening)?

@tacri any insights here?

**Comment by don4of4** [comment] 2020-11-19 03:43
@clearab Yes, that's the crazy thing, this happens on multiple computers, even ones that are totally virgin to the old version of the app/bot.  For example, I just opened edge, clicked this brand new app (I created above) and the full set of menus are there.  

![image](https://user-images.githubusercontent.com/871843/99618462-f3892380-29e6-11eb-8dc1-f7b4da74ef1c.png)

**Comment by clearab** [comment] 2020-11-19 03:52
Ok, seems like a caching bug on your user profile then. Can you try an explicit logout / login and see if that at least unblocks you for now? Do you know if any of your users are experiencing the same?

**Comment by don4of4** [comment] 2020-11-19 03:54
All users -- hence the issue.  Once bot menu's turn on -- it's an immutable plague for all that touch the bot.

**Comment by clearab** [comment] 2020-11-19 03:57
Ok, thanks for all the additional info, and my apologies for the 20 questions. I'll get the right folks from the Teams group engaged to get this resolved.

**Comment by don4of4** [comment] 2020-11-19 04:06
Thank you, I appreciate the help.  For completeness -- this also survives log out / log in.  It appears my only option right now is to pull the entire app with some admin policy, and do a force install of a _new_ app.  

_That really puts this bug in the "severe" or "showstopper" bucket for me.  IMO this menu feature should be pulled if the menus are accidentally immutable._

**Comment by clearab** [comment] 2020-11-20 17:05
The Teams group was able to repro this successfully, and have filed a bug. I will follow up again when I have an ETA for a fix.

**Comment by clearab** [comment] 2021-01-11 23:01
My apologies for the delayed response - the Teams group is continuing to work on a fix for this issue, but with no ETA yet.

**Closed** 2022-01-11 22:11 UTC
Labels: bug, customer-replied-to, customer-reported, Bot Services, ExemptFromDailyDRIReport, Area: Teams
