### ISSUE TITLE
Redirect the message Directly To Teams Chatbot On Behalf Of User

### ISSUE THREAD

**Issue by amreshgarg21** [microsoft/botframework-sdk#6609] opened 2023-08-25 10:51 UTC
Is there a way through which we can redirect the messages to the team's chatbot on behalf of the user using DeepLink Url?

I tried using the MS Teams deep link:
https://teams.microsoft.com/l/chat/0/0?&message=Hi, this is a predefined message from hyperlink.

But here the user needs to press enter key or send button in order to send the message.
I want to directly send it without pressing the send button in MS Teams.

![image](https://github.com/microsoft/botframework-sdk/assets/89493897/7522ee1b-759c-4078-871b-ee42bf1fb2b1)

If a user has previously directed certain messages to the chat placeholder, any subsequent redirections will occur without overwriting the existing text within the placeholder for the same user. User session can be refreshed or closed after the user clicks on that particular URL and chats with Chatbot <so that if they user re-clicks on that link, the deep link works>>
Can we do any workaround for this as well?

**Comment by dmvtech** [comment] 2024-01-23 00:02
Duplicate of https://github.com/microsoft/botframework-sdk/issues/6607

**Closed by dmvtech** 2024-01-23 00:02 UTC
