### ISSUE TITLE
Errors occured during link unfurling

### ISSUE THREAD

**Issue by chikaishiro** [microsoft/botframework-sdk#6532] opened 2022-08-24 03:28 UTC
## Version
![H0{J7N{9 ~E4(OM3O9~4FIX](https://user-images.githubusercontent.com/26539304/186309753-4e6430d4-60e5-4ce3-833a-cf1567de641f.png)

## Describe the bug
Errors occured during link unfurling. 
My link unfurling works when I create A new message extension app with [TeamsToolkit](https://github.com/OfficeDev/TeamsFx) and the sample code for message extension is [here](https://github.com/OfficeDev/TeamsFx-Samples/tree/dev/hello-world-bot) 
I added an output in the entry of the link unfurling part.
![image](https://user-images.githubusercontent.com/26539304/186313338-2aed0fb5-a94f-419d-b817-c893c1975f07.png)
But when I run local debug the second time, link unfurling does not seems to work. My bot can not receive request and there is no output of `query.url` .
When my bot cannot receive link unfurling query, I checked the console output of Edge and it outputs the errors below. Since I didn't know which output contributed to the failure. I took a screenshot of all of them.
![image](https://user-images.githubusercontent.com/26539304/186311695-be066ea8-af5d-471d-972a-72ef2a68f216.png)
I think this bug may cannot be reproduced and what really helps is the output above. 
## To Reproduce
1. Go to VSCode and install extension `Teams Toolkit`
2. Click on `Create a new teams App`
![image](https://user-images.githubusercontent.com/26539304/186311406-e13d698c-b71a-41a5-8df1-7ff495163c25.png)
3. Click on `Create a new teams App`  in the menu
![image](https://user-images.githubusercontent.com/26539304/186311571-0605f616-a4f3-49cd-b8b2-65ca93479d92.png)
4. Select `Message Extension` and `TypeScript`. Then input the directory and the name of the App
![image](https://user-images.githubusercontent.com/26539304/186312369-f7837b3b-3e03-4b6e-a702-558f93cfc3fa.png)
5. Modify file `templates/appPackage/manifest.template.json`
![image](https://user-images.githubusercontent.com/26539304/186316985-40a4e8c2-a798-4d20-adcf-4e829bc1c8e5.png)
6. Press `F5` to start local debugging. When a new debug Edge window is opened, stop the local debugging session.
7. Start local debugging again and my link unfurling does not work.

**Comment by ramfattah** [comment] 2022-08-24 17:56
Hi @chikaishiro, I'm investigating this one.

**Comment by ramfattah** [comment] 2022-08-30 00:36
Hi @chikaishiro, 

### Reproduce

Using this [TeamsToolkit](https://github.com/OfficeDev/TeamsFx), I was able to repro. 

#

### Not Reproduce

After digging deeper, I was NOT able to repro the issue if using the sample [55.teams-link-unfurling](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/55.teams-link-unfurling) from
 the [BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples) repository. 


Sample [55.teams-link-unfurling](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/55.teams-link-unfurling) works as expected after pasting link:
![image](https://user-images.githubusercontent.com/38049078/187322041-213ec99e-11f2-46ed-9669-f322f291a9d1.png)

**Comment by ramfattah** [comment] 2022-08-30 00:39
Looks like the root cause for this issue is when using [TeamsToolkit](https://github.com/OfficeDev/TeamsFx) to create Link Unfurling message extension app.

The sample [55.teams-link-unfurling](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/55.teams-link-unfurling) from [BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples) repository works as expected without issues.

**Comment by chikaishiro** [comment] 2022-08-30 02:42
Thanks a lot. So I'll investigate that further. And does the error output from console provide any important information?

**Comment by ramfattah** [comment] 2022-08-30 19:03
@chikaishiro, I tested in Teams desktop application client.

**Comment by ramfattah** [comment] 2022-08-30 19:04
Closing as this issue as it is not reproducible in [BotBuilder-Samples](https://github.com/microsoft/BotBuilder-Samples) repository.

**Closed by ramfattah** 2022-08-30 19:04 UTC
Labels: customer-replied-to, customer-reported, Bot Services

**Comment by ramfattah** [comment] 2022-08-30 19:07
Not related to Bot Framework SDK. 

@chikaishiro, Please open an issue in the TeamsToolkit repository here https://github.com/OfficeDev/TeamsFx/issues
