### ISSUE TITLE
Latest emulator could not connect to a local bot

### ISSUE THREAD

**Issue by ygizhitsa** [microsoft/botframework-sdk#5579] opened 2019-09-05 18:40 UTC
TO reproduce
- Create new V4 bot project from Echo or Core template 
- start bot locally
- start Emulator 
- connect to bot
 - for echo bot type and send a message 

Other info
- ngrok is configured and bypass for local checkbox checked 
- postman post reaching controller

[14:33:41]Emulator listening on http://localhost:57870
[14:33:41]ngrok not configured (only needed when connecting to remotely hosted bots)
[14:33:41]Connecting to bots hosted remotely
[14:33:41]Edit ngrok settings
[14:33:41]
[14:33:41]POST403directline.conversationUpdate
[14:33:41]
[14:33:41]POST403directline.conversationUpdate
[14:33:41]POST200directline.startConversation

![image](https://user-images.githubusercontent.com/16059989/64369834-2534eb00-cfeb-11e9-840f-46c54c6dc3b7.png)

**Comment by tdurnford** [comment] 2019-09-05 22:03
Closing as this is a duplicate of https://github.com/microsoft/BotFramework-Emulator/issues/1837

**Closed by tdurnford** 2019-09-05 22:03 UTC
