### ISSUE TITLE
Cannot read property 'isChannelConversation' of undefined

### ISSUE THREAD

**Issue by GDreyV** [microsoft/botframework-sdk#5811] opened 2020-04-21 18:25 UTC
Hello! I'm trying to use `ActionTypes.PostBack` on card returned from `OnTeamsMessagingExtensionSelectItemAsync` with following code:
```csharp
var card = new ThumbnailCard
  {
    Title = project.Name,
    Buttons = new List<CardAction>
      {
        new CardAction { Type = ActionTypes.PostBack, Title = "Subscribe", Value = query },
      },
  };
var attachment = new MessagingExtensionAttachment { ContentType = ThumbnailCard.ContentType, Content = card, };
return Task.FromResult(new MessagingExtensionResponse
  {
    ComposeExtension = new MessagingExtensionResult
      {
        Type = "result",
        AttachmentLayout = "list",
        Attachments = new List<MessagingExtensionAttachment> { attachment }
      }
  });
```
but when I press the button in browser I'm getting following error and nothing happens:
```
TypeError: Cannot read property 'isChannelConversation' of undefined
    at t.getAppDefinitionFromCard (https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-c7c53b37.js:3:308254)
    at t.logTelementryForCardAction (https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-c7c53b37.js:3:276083)
    at _.debounce.trailing (https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-c7c53b37.js:3:148902)
    at e (https://statics.teams.cdn.office.net/hashedjs/2-vendor.min-68b363d0.js:64:245)
    at f (https://statics.teams.cdn.office.net/hashedjs/2-vendor.min-68b363d0.js:65:49)
    at t.e.buttonClicked (https://statics.teams.cdn.office.net/hashedjs/3.2-app.min-c7c53b37.js:3:148400)
```
Am I sending the card wrong or is it application issue?

**Comment by tonyanziano** [comment] 2020-04-22 18:03
@dmvtech can you take a look at this please?

**Comment by dmvtech** [comment] 2020-04-22 18:06
Kyle is looking into this one.

**Comment by tonyanziano** [comment] 2020-04-22 18:08
@dmvtech awesome thanks, going to close this is a dupe of https://github.com/microsoft/BotBuilder-Samples/issues/2335

**Closed by tonyanziano** 2020-04-22 18:08 UTC
Labels: Bot Services, customer-reported
