### ISSUE TITLE
Adaptive card images are not showing in MS Teams where as showing in emulator and webchat

### ISSUE THREAD

**Issue by venkatesh143293** [microsoft/botframework-sdk#5750] opened 2020-02-16 06:55 UTC
Adaptive card images are not showing in MS Teams where as showing in emulator and web chat.

below is my payload
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "size": "Medium",
      "weight": "Bolder",
      "color": "Accent",
      "text": "Rate your experience!"
    },
    {
      "type": "TextBlock",
      "separator": true,
      "text": "Please rate your experience! Your feedback is very appreciated and will help improve your experience in the future. ",
      "wrap": true
    },
    {
      "type": "ColumnSet",
      "spacing": "Medium",
      "columns": [
        {
          "type": "Column",
          "selectAction": {
            "type": "Action.Submit",
            "data": "awful"
          },
          "items": [
            {
              "type": "Image",
              "horizontalAlignment": "Center",
              "url": "https://upload.wikimedia.org/wikipedia/commons/1/18/Five-pointed_star.svg",
              "size": "small"
            },
            {
              "type": "TextBlock",
              "horizontalAlignment": "Center",
              "text": "Awful"
            }
          ],
          "width": "stretch"
        },
        {
          "type": "Column",
          "selectAction": {
            "type": "Action.Submit",
            "data": "bad"
          },
          "items": [
            {
              "type": "Image",
              "horizontalAlignment": "Center",
              "url": "https://upload.wikimedia.org/wikipedia/commons/1/18/Five-pointed_star.svg",
              "size": "small"
            },
            {
              "type": "TextBlock",
              "horizontalAlignment": "Center",
              "text": "Bad"
            }
          ],
          "width": "stretch"
        },
        {
          "type": "Column",
          "selectAction": {
            "type": "Action.Submit",
            "data": "Ok"
          },
          "items": [
            {
              "type": "Image",
              "horizontalAlignment": "Center",
              "url": "https://upload.wikimedia.org/wikipedia/commons/1/18/Five-pointed_star.svg",
              "size": "small"
            },
            {
              "type": "TextBlock",
              "horizontalAlignment": "Center",
              "text": "Ok"
            }
          ],
          "width": "stretch"
        },
        {
          "type": "Column",
          "selectAction": {
            "type": "Action.Submit",
            "data": "good"
          },
          "items": [
            {
              "type": "Image",
              "horizontalAlignment": "Center",
              "url": "https://upload.wikimedia.org/wikipedia/commons/1/18/Five-pointed_star.svg",
              "size": "small"
            },
            {
              "type": "TextBlock",
              "horizontalAlignment": "Center",
              "text": "Good"
            }
          ],
          "width": "stretch"
        },
        {
          "type": "Column",
          "selectAction": {
            "type": "Action.Submit",
            "data": "terrific"
          },
          "items": [
            {
              "type": "Image",
              "horizontalAlignment": "Center",
              "url": "https://upload.wikimedia.org/wikipedia/commons/1/18/Five-pointed_star.svg",
              "size": "small"
            },
            {
              "type": "TextBlock",
              "horizontalAlignment": "Center",
              "text": "Terrific"
            }
          ],
          "width": "stretch"
        }
      ]
    }
  ],  
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}

Emulator
![image](https://user-images.githubusercontent.com/7261792/74600382-d372af80-50b6-11ea-9235-9e3a8e373b41.png)
Web Chat
![image](https://user-images.githubusercontent.com/7261792/74600399-16348780-50b7-11ea-8c65-06cb9009c586.png)

MS Teams
![image](https://user-images.githubusercontent.com/7261792/74600410-319f9280-50b7-11ea-807a-b594cb9958c4.png)

**Comment by mdrichardson** [comment] 2020-02-17 17:38
@venkatesh143293 Teams doesn't support SVG images. You could replace it with something [like this](https://icons-for-free.com/iconfiles/png/512/mark+opinion+rating+star+icon-1320191205647153700.png)

**Comment by mdrichardson** [comment] 2020-02-21 23:56
@venkatesh143293 Were you able to get this working with non-SVGs?

**Comment by venkatesh143293** [comment] 2020-02-22 01:50
@mdrichardson Thanks for the response. I am bale to see the non svgs, but I am seeing the below difference in teams vs emulator.
From Emulator if I click on the image the respected text is displaying in the dialogue
![emulator](https://user-images.githubusercontent.com/7261792/75084067-95a4d980-5543-11ea-81df-c0c061c1b885.png)

Where as from teams, if I click on that image again the same adaptive card is displaying
![image](https://user-images.githubusercontent.com/7261792/75084102-cedd4980-5543-11ea-892b-aa4ccbfd4002.png)

**Comment by mdrichardson** [comment] 2020-02-24 15:34
@venkatesh143293 Interesting. Can you copy/paste your current Adaptive Card JSON so I can do some troubleshooting? I want to make sure we're working with the exact same code.

**Comment by venkatesh143293** [comment] 2020-02-24 16:16
@mdrichardson Thanks..
This is the current JSON I am using
{
  "type": "AdaptiveCard",
  "body": [
    {
      "type": "TextBlock",
      "size": "Medium",
      "weight": "Bolder",
      "color": "Accent",
      "text": "Rate your experience!"
    },
    {
      "type": "TextBlock",
      "separator": true,
      "text": "Please rate your experience! Your feedback is very appreciated and will help improve your experience in the future. ",
      "wrap": true
    },
    {
      "type": "ColumnSet",
      "spacing": "Medium",
      "columns": [
        {
          "type": "Column",
          "selectAction": {
            "type": "Action.Submit",
            "data": "awful"
          },
          "items": [
            {
              "type": "Image",
              "horizontalAlignment": "Center",
              "url": "https://icons-for-free.com/iconfiles/png/512/mark+opinion+rating+star+icon-1320191205647153700.png",
              "size": "small"
            },
            {
              "type": "TextBlock",
              "horizontalAlignment": "Center",
              "text": "Awful"
            }
          ],
          "width": "stretch"
        },
        {
          "type": "Column",
          "selectAction": {
            "type": "Action.Submit",
            "data": "bad"
          },
          "items": [
            {
              "type": "Image",
              "horizontalAlignment": "Center",
              "url": "https://icons-for-free.com/iconfiles/png/512/mark+opinion+rating+star+icon-1320191205647153700.png",
              "size": "small"
            },
            {
              "type": "TextBlock",
              "horizontalAlignment": "Center",
              "text": "Bad"
            }
          ],
          "width": "stretch"
        },
        {
          "type": "Column",
          "selectAction": {
            "type": "Action.Submit",
            "data": "Ok"
          },
          "items": [
            {
              "type": "Image",
              "horizontalAlignment": "Center",
              "url": "https://icons-for-free.com/iconfiles/png/512/mark+opinion+rating+star+icon-1320191205647153700.png",
              "size": "small"
            },
            {
              "type": "TextBlock",
              "horizontalAlignment": "Center",
              "text": "Ok"
            }
          ],
          "width": "stretch"
        },
        {
          "type": "Column",
          "selectAction": {
            "type": "Action.Submit",
            "data": "good"
          },
          "items": [
            {
              "type": "Image",
              "horizontalAlignment": "Center",
              "url": "https://icons-for-free.com/iconfiles/png/512/mark+opinion+rating+star+icon-1320191205647153700.png",
              "size": "small"
            },
            {
              "type": "TextBlock",
              "horizontalAlignment": "Center",
              "text": "Good"
            }
          ],
          "width": "stretch"
        },
        {
          "type": "Column",
          "selectAction": {
            "type": "Action.Submit",
            "data": "Awesome"
          },
          "items": [
            {
              "type": "Image",
              "horizontalAlignment": "Center",
              "url": "https://icons-for-free.com/iconfiles/png/512/mark+opinion+rating+star+icon-1320191205647153700.png",
              "size": "small"
            },
            {
              "type": "TextBlock",
              "horizontalAlignment": "Center",
              "text": "Awesome"
            }
          ],
          "width": "stretch"
        }
      ]
    }
  ],  
  "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
  "version": "1.0"
}

**Comment by mdrichardson** [comment] 2020-02-24 16:24
@venkatesh143293 I'm unable to reproduce this and the card behaves as expected. What versions of botbuilder are you running? Can you copy/paste the code surrounding whatever you use to send the card?

**Comment by venkatesh143293** [comment] 2020-02-24 16:35
var welcomeCard = CreateAdaptiveCardAttachment();
                            var opts = new PromptOptions
                            {
                                Prompt = new Activity
                                {
                                    Attachments = new List<Attachment>() { welcomeCard },
                                    Type = ActivityTypes.Message,                                   
                                }
                            };
                            return await stepContext.PromptAsync(nameof(TextPrompt), opts);


 

        // Load attachment from file.
        private Attachment CreateAdaptiveCardAttachment()
        {
            // combine path for cross platform support
            string[] paths = { ".", "Cards", "StarRating.json" };
            string fullPath = Path.Combine(paths);
            var adaptiveCard = File.ReadAllText(fullPath);
            return new Attachment()
            {
                ContentType = "application/vnd.microsoft.card.adaptive",
                Content = JsonConvert.DeserializeObject(adaptiveCard),
            };
        }

**Comment by venkatesh143293** [comment] 2020-02-24 16:36
@mdrichardson , for me also its working as expected in emulator and web chat I am facing this when I deployed to MS Teams

**Comment by venkatesh143293** [comment] 2020-02-24 16:37
I am working on Bot Framework V4

**Comment by mdrichardson** [comment] 2020-02-24 16:39
@venkatesh143293 It is working as expected for me in Teams.

1. Is the prompt being called again in Teams when the card is clicked? That would be my guess. How is the prompt and dialog called in your code?

2. What specific versions are the Botbuilder packages?

**Comment by venkatesh143293** [comment] 2020-02-24 16:44
@mdrichardson Yes.. you said it correct. The prompt is calling again when  clicked on the card. I already shared the code how I am calling the prompt in my code
var welcomeCard = CreateAdaptiveCardAttachment();
                            var opts = new PromptOptions
                            {
                                Prompt = new Activity
                                {
                                    Attachments = new List<Attachment>() { welcomeCard },
                                    Type = ActivityTypes.Message,                                   
                                }
                            };
                            return await stepContext.PromptAsync(nameof(TextPrompt), opts);

**Comment by mdrichardson** [comment] 2020-02-24 16:45
@venkatesh143293 Right, but how do you get to the code you included? What's calling that dialog? If the prompt is what's being called again, the problem is in the code, not the card.

**Comment by venkatesh143293** [comment] 2020-02-24 16:56
@mdrichardson this are the two steps the card is calling
  private async Task<DialogTurnResult> FinalStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {

            if (stepContext.Result != null)
            {
                var welcomeCard = CreateAdaptiveCardAttachment();
                var opts = new PromptOptions
                {
                    Prompt = new Activity
                    {
                        Attachments = new List<Attachment>() { welcomeCard },
                        Type = ActivityTypes.Message,
                    }
                };
            }

        }
 private async Task<DialogTurnResult> FeedbackStepAsync(WaterfallStepContext stepContext, CancellationToken cancellationToken)
        {
            //var entitiDetails = (EntitiDetails)stepContext.Options;
            FeedbackEntity feedbackEntity = new FeedbackEntity();
            feedbackEntity.PartitionKey = stepContext.Context.Activity.From.Name;
            feedbackEntity.RowKey = guid;
            feedbackEntity.Role = getUserRole(stepContext.Context.Activity.From.Id);
            feedbackEntity.Status = "true";
            feedbackEntity.FeedBack = stepContext.Result.ToString();
            feedbackEntity.Intent = strIntent;
            StorageHelper storageHelper = new StorageHelper();
            await storageHelper.StoreFeedback(Configuration, feedbackEntity);
            await stepContext.Context.SendActivityAsync(MessageFactory.Text("Thank you for your feedback"), cancellationToken);
            return await stepContext.EndDialogAsync(cancellationToken: cancellationToken);
        }
 private Attachment CreateAdaptiveCardAttachment()
        {
            // combine path for cross platform support
            string[] paths = { ".", "Cards", "StarRating.json" };
            string fullPath = Path.Combine(paths);
            var adaptiveCard = File.ReadAllText(fullPath);
            return new Attachment()
            {
                ContentType = "application/vnd.microsoft.card.adaptive",
                Content = JsonConvert.DeserializeObject(adaptiveCard),
            };
        }

**Comment by mdrichardson** [comment] 2020-02-24 16:59
@venkatesh143293 How is the *dialog* being called? What code leads to the dialog that displays the card? Where are you calling either `Dialog.Run` or `beginDialog`.

What versions are your botbuilder packages?

**Comment by venkatesh143293** [comment] 2020-02-24 17:00
I am calling BeginDialog

**Comment by venkatesh143293** [comment] 2020-02-24 17:02
its waterfalldialog framework starting with begin dailog and ending with end dialog

**Comment by mdrichardson** [comment] 2020-02-24 17:18
@venkatesh143293 Please include the code surrounding your call to `BeginDialog`.

**Comment by venkatesh143293** [comment] 2020-02-24 17:28
@mdrichardson 
1. I have two classes one is MainDialog.cs and ActionDialog.cs
below are the steps involved in main dialog
public MainDialog(IConfiguration configuration, ILogger<MainDialog> logger, IHttpClientFactory httpClientFactory)//
            : base(nameof(MainDialog))
        {
            Configuration = configuration;
            Logger = logger;
            _httpClientFactory = httpClientFactory;

            AddDialog(new TextPrompt(nameof(TextPrompt)));
            AddDialog(new ConfirmPrompt(nameof(ConfirmPrompt)));
            AddDialog(new ActionDialog(configuration, logger));
            AddDialog(new ChoicePrompt(nameof(ChoicePrompt)));
            AddDialog(new WaterfallDialog(nameof(WaterfallDialog), new WaterfallStep[]
            {
                IntroStepAsync,
                ActStepAsync,
                FinalStepAsync,
                FeedbackStepAsync,

            }));
2. I am calling BeginDailog in from ActStep which is calling ActionDailog.
 return await stepContext.BeginDialogAsync(nameof(ActionDialog), eDetails, cancellationToken);

3. In ActionDialog.cs I have the below steps are involved

 public ActionDialog(IConfiguration configuration, ILogger<MainDialog> logger)
            : base(nameof(ActionDialog))
        {
            Configuration = configuration;
            Logger = logger;
            AddDialog(new TextPrompt(nameof(TextPrompt)));
            AddDialog(new ConfirmPrompt(nameof(ConfirmPrompt)));
            AddDialog(new ChoicePrompt(nameof(ChoicePrompt)));
            AddDialog(new DateResolverDialog());
            AddDialog(new WaterfallDialog(nameof(WaterfallDialog), new WaterfallStep[]
            {
                DestinationStepAsync,
                PortfolioStepAsync,
                EnvironmentStepAsync,
                TagStepAsync,
                DbInstanceStepAsync,
                ConfirmStepAsync,
                CaptureEmailStepAsync,
                FinalStepAsync,
            }));
4. from Final step I am calling EndDialog which agian going back to Finalstep in MainDialog
return await stepContext.EndDialogAsync(entitiDetails, cancellationToken);

5. In MainDailog finalstep I am calling that card prompt,

**Comment by mdrichardson** [comment] 2020-02-24 17:33
How is MainDialog being called? It may be easiest to zip up all of your code or add it to a repo and link me to it. For some reason, it appears your Main Dialog is calling your ActionDialog after the card is clicked. We need to figure out why and it looks like it will take a *lot* of code debugging to do so.

**Comment by venkatesh143293** [comment] 2020-02-24 17:44
@mdrichardson Here I am attaching my code. I removed some of my service end points and keys from the code
[Bot.zip](https://github.com/microsoft/botframework-sdk/files/4245945/Bot.zip)

**Comment by mdrichardson** [comment] 2020-02-24 18:23
@venkatesh143293 Alright. Looks like you don't have the necessary handling required for Adaptive Card inputs.

See [this blog post](https://blog.botframework.com/2019/07/02/using-adaptive-cards-with-the-microsoft-bot-framework/) and the section at the bottom titled, **Adaptive Cards in Teams**.

I wasn't aware, until now, that Teams handled these so differently. But basically, when you click the card in Teams, it's sending a message activity with a null Text and blank Value, so the TextPrompt with your Adaptive Card attachment gets re-prompted. 

Sorry for the runaround, but there's a fix, at least.

Alternatively to the blog recommendation, you can make your `data` property in your card an object:

```json
"data": { "value": "bad" }
```

Then, in `OnTurnAsync`, you'd do something like [this](https://stackoverflow.com/questions/55061325/how-to-retrieve-adaptive-cards-form-submission-in-subsequent-waterfall-step/55066910#55066910):

```csharp
var activity = turnContext.Activity;

if (string.IsNullOrWhiteSpace(activity.Text) && activity.Value != null)
{
    activity.Text = JsonConvert.SerializeObject(activity.Value);
}
```

**Comment by mdrichardson** [comment] 2020-02-26 16:02
@venkatesh143293 I'm going to close this, as I believe this issue has been fully addressed. Feel free to re-open if you disagree.

**Closed by mdrichardson** 2020-02-26 16:02 UTC
Labels: Bot Services, customer-replied-to, customer-reported

**Comment by venkatesh143293** [comment] 2020-02-26 18:25
@mdrichardson Thank you so much for the help. Teams is handling this differently. Now the issue is resolved. I added the data field like below
data: {
              "msteams": {
                "type": "imBack",
                "value": "Awesome"
              }
            }

**Comment by deepa-singh-maersk** [comment] 2022-09-26 10:41
{"id":"","messageLink":"","error":"Bot hasn't been installed for user RequestId : f301f2ad-564f-4f1c-a42a-13b82c2e5b2d"}
getting this error in power virtual agent privew chat bot 
this is working fine all of the sudden it start failing with above message

Can anyone help me with the solution
