### ISSUE TITLE
Add Custom Commands application as a skill in Bot framework composer application

### ISSUE THREAD

**Issue by ridasaleem0** [microsoft/botframework-sdk#6514] opened 2022-05-31 11:11 UTC
The documentation (https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/how-to-custom-commands-integrate-remote-skills) gives an idea about how to export the Custom Commands application as a skill, however, there is no skills tab available in the Speech studio under Custom commands settings.

Is there a way to export our commands app as a skill inside the bot framework application?

**Comment by stevkan** [comment] 2022-05-31 18:04
Closing as duplicate of https://github.com/microsoft/BotFramework-Composer/issues/9212.

**Closed by stevkan** 2022-05-31 18:04 UTC
Labels: customer-replied-to, customer-reported, Bot Services
