### ISSUE TITLE
How to subscribe to the refresh token event

### ISSUE THREAD

**Issue by IonutArhire** [microsoft/botframework-sdk#5692] opened 2019-12-09 11:10 UTC
The problem is that I need to be able to subscribe to the token refresh event and I can't figure out how.

I know people advise on subscribing to connectionStatus$ and handling the ConnectionStatus.ExpiredToken case, but the execution never enters that case when refreshing happens, it only enters that case when I try to initialize the bot with an expired token.

The token refresh event is getting triggered every 15 minutes by the library itself but there is no observable that will allow me to subscribe to it to get the newly refreshed token. The workaround I found for now is that I set an interval of 15 min (by using setInterval()) for checking if the token used by the connection has changed.

Any idea?

The code is in pure, vanilla, javascript. Library code I'm using: https://cdn.botframework.com/botframework-webchat/master/webchat.js

**Comment by mdrichardson** [comment] 2019-12-09 16:29
Closing as duplicate of [this SO question](https://stackoverflow.com/questions/59247586/how-to-subscribe-to-the-refresh-token-event), which is a more appropriate forum for How-To questions.

**Closed by mdrichardson** 2019-12-09 16:29 UTC
