### ISSUE TITLE
The embeded Hyperlinks are not opening in Google Chrome Through MS-Teams Bot

### ISSUE THREAD

**Issue by shivajipotnuru** [microsoft/botframework-sdk#6431] opened 2021-11-23 12:39 UTC
## Version
Bot Framework - V4

## Describe the bug
The following scenario I've tried
1. The Following answer hyperlink is opening on the MS-Teams app

![image](https://user-images.githubusercontent.com/33416266/143023579-b485ad99-c744-4ea3-94f1-5321e91fe85a.png)

Answer Markdown Syntax in the QnA Maker
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/33416266/143024313-802eb7e7-14da-445f-bfd3-92d842083ac7.png)
 
2. The Following answer is not opening on the MS-Teams app( embedded hyperlink is changed  to Bold/Italic)

![image](https://user-images.githubusercontent.com/33416266/143024874-4917dff9-d3d3-406c-a260-fadbe12d910e.png)

Answer Markdown Syntax in the QnA Maker

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/33416266/143024809-0939e651-3b86-4b26-af4d-de3cae646869.png)

**Note:**  
 1. Opening MS teams bot in a Firefox Browser, then all scenarios are working.
 2. Opening MS teams Bot in a Chrome Browser, then second point is not working as I mentioned above

**Comment by anishprasad01** [comment] 2021-11-26 00:51
Hi @shivajipotnuru,

I attempted to reproduce your issue using the following steps:

- Create a QnA Knowledge Base
- Add a custom question with an answer that has a bolded word via markdown formatting
- Deploy the KB to Azure
- Add the KB to a bot (just followed the auto prompts in QnA Maker -> Azure)
- Enabled the Microsoft Teams channel for the bot
- Attempt to communicate with the bot in Chrome and in the Emulator

As you can see in the below images, I added a simple question `What is a cat?` which results in the answer `A **feline**` that links to a simple Google search. Clicking this link opens a new tab with that Google search.

<img width="531" alt="image" src="https://user-images.githubusercontent.com/33945547/143511204-647760c6-2c89-4a7e-b1e2-96e58e9955d8.png">

<img width="431" alt="image" src="https://user-images.githubusercontent.com/33945547/143511184-3c0eea32-4117-4205-8437-5723d7bf356a.png">

As that appears to be working, I need more information from you about your bot to try and isolate your problem.

- How was this bot built?
- What language did you use?
- What version of each tool are you using? (.NET, NodeJS, Browser, Composer, if used)
- Are there any restrictions or apps in your Teams or your browser that might misinterpret markdown syntax?
- Any patterns to this issue? When did it start?
- Anything else of relevance?

**Comment by shivajipotnuru** [comment] 2021-11-26 06:40
HI @anishprasad01 

- we are using .NET core 3.1(LTS)
- we built our bot using C#
- Our bot works on the Teams  ( web & app)
- Chrome Version 96.0.4664.45 (Official Build) (64-bit)
- Adaptive Card - 2.5.1
- Our QnA pairs have metatags as well
- This issue we are facing for the past few days(5-10), we have done the  internal testing & found out that embedded hyperlinks are opening in the Firefox browser but not on chrome
- The only option we have left is to change the embedded hyperlinks to Normal case, then only those links are redirecting/opening. 
- In the Client Teams App( default browser is set to Firefox) all the links are opening fine.
- We disable all the chrome extensions and tried as well, but no use in our case.
- we have around 550+ QnA Pairs in our QNA maker
- Around 220+ QnA Pairs have the Bold/Italic Embedded hyperlinks.



CC: @rajeeshmenoth

**Comment by anishprasad01** [comment] 2021-11-26 16:07
Your original issue never mentioned Adaptive Cards, so I didn't test for that yet. In order to test as accurately as possible, can you tell me what exactly your application's logic flow is? What is it supposed to do when a user asks a question?

You also mentioned it started about 5-10 days ago. Did you make any big changes to your bot's code or your development or test environments in that time? Update any tools aside from the browsers?

**Comment by 53645** [comment] 2021-11-26 17:57
My application name  is teleavatar This application is video col and massaging chate and status sam to sam whatsapp I need bot for otp and api id and Hash please help me

**Comment by rajeeshmenoth** [comment] 2021-11-27 03:59
Hi @anishprasad01,

It's a FAQ bot and there are no code changes happening yet for the last two weeks. All these issues were encountered after the chrome latest updates ( [Chrome updates](https://chromereleases.googleblog.com/)).

## FAQ Bot Example:

1. User is asking payroll related details in MS Team Bot.
2. The response contains payroll document details ( Embedded as URL ).
3. All responses return as an attachment ( Adding this response in attachment and after that posting using send activity ). 
4. AdaptiveCard version is 1.2

**Note:** This issue is happening for enlarging the image as well in chrome browser  ( While clicking the image enlarge icon it shows the blank screen in the MS Team - an example is given below)

`{
    "type": "AdaptiveCard",
     "body": [
          {
            "type": "Image",
            "url": "https://picsum.photos/200/200?image=110",
            "msTeams": {
              "allowExpand": true
            }
          },
     ],
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.2"
}`

**Comment by anishprasad01** [comment] 2021-12-01 18:58
@rajeeshmenoth

A clarification question. Is your QnA Knowledge Base returning just the formatted hyperlink whcih you are then inserting into an Adaptive Card, or is it returning the entire JSON representing an Adaptive Card?

**Comment by anishprasad01** [comment] 2021-12-01 23:51
Hi @shivajipotnuru & @rajeeshmenoth,

After further investigation, I was able to reproduce your issue. Fortunately, I believe I also have a workaround for you.

When you added markdown formatting to your QnA response, you did so in the standard manner, like this: `this is the [**response**](hyperlink)`. As your issue pointed out, when this response is placed into an Adaptive Card and sent by the bot to the user, the link does not function in Microsoft Teams (though it will work in other channels, such as Web Chat).

However, my investigation has revealed that if you instead format your QnA responses like this: `this is the **[response](hyperlink)**`, you will still get a formatted hyperlink (see image below for an example), and it will now function in Microsoft Teams.

Give this workaround a try in your application and let me know if it works.

![image](https://user-images.githubusercontent.com/33945547/144332223-f8f8edea-2c9f-4b16-8dfe-36ca6a021780.png)

**Comment by rajeeshmenoth** [comment] 2021-12-02 04:33
> @rajeeshmenoth
> 
> A clarification question. Is your QnA Knowledge Base returning just the formatted hyperlink which you are then inserting into an Adaptive Card within the bot's code, or is it returning the entire JSON representing an Adaptive Card?

@anishprasad01 Yes, Whatever output we are getting from QnA Maker that directly inserted into Adaptive Card.


**Note:** We are using Adaptive Card C# objects instead of JSON format.

**Comment by shivajipotnuru** [comment] 2021-12-02 05:18
> Hi @shivajipotnuru & @rajeeshmenoth,
> 
> After further investigation, I was able to reproduce your issue. Fortunately, I believe I also have a workaround for you.
> 
> When you added markdown formatting to your QnA response, you did so in the standard manner, like this: `this is the [**response**](hyperlink)`. As your issue pointed out, when this response is placed into an Adaptive Card and sent by the bot to the user, the link does not function in Microsoft Teams (though it will work in other channels, such as Web Chat).
> 
> However, my investigation has revealed that if you instead format your QnA responses like this: `this is the **[response](hyperlink)**`, you will still get a formatted hyperlink (see image below for an example), and it will now function in Microsoft Teams.
> 
> Give this workaround a try in your application and let me know if it works.
> 
> ![image](https://user-images.githubusercontent.com/33945547/144332223-f8f8edea-2c9f-4b16-8dfe-36ca6a021780.png)

@anishprasad01 


When we are getting a huge document as a response, we are having multiple hyperlinks related to HR policies, so in the code side, we can't format this many links in a single shot.

We have gone through your approach & we are facing the same issue.

1.  As you mentioned asterisk * are added in the following way
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/33416266/144361602-e9e001f8-a945-40f5-87ee-fcf917037fdc.png)
2. Now I'm clicking outside of the editor window
![MicrosoftTeams-image (7)](https://user-images.githubusercontent.com/33416266/144361706-eaec0138-3af9-4897-8149-4d0ca745e0d8.png)
3. Now I'm clicking markdown view of the same editor, it's automatically moving asterisk inside the square brackets
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/33416266/144361801-802d4442-bcf6-4b5d-83e7-b1e1d17bc443.png)

**Note**: if you are opening the MS-teams bot in firefox/another browser tab this particular scenarios are working fine. 
In the hosted MS-teams app is not working.

We are expecting a quick fix for the customer needs. Is there any update on the [enlargeing Images issue]( https://github.com/MicrosoftDocs/msteams-docs/issues/4681)?

**Comment by anishprasad01** [comment] 2021-12-02 16:06
@rajeeshmenoth, The test I performed also uses C# Adaptive Card objects, not JSON.

@shivajipotnuru, Yes, I am aware that it appears this way when you click back into it, but if you format it the way I outlined, train, and publish it, it should still work. I tested this within the Microsoft Teams app, and it functions correctly despite the erroneous appearance in the QnA Maker portal.

As far as the enlarging images issue goes, that appears to be a Teams issue. I noticed that someone from Microsoft has already commented that it is a reproducible bug and that it is being looked into, so I would suggest you continue to collaborate on that issue while they attempt to fix the bug.

**Comment by anishprasad01** [comment] 2021-12-06 20:59
Were you able to test this workaround as described in your environment? Knowing the results of your test would help us narrow down potential bugs.

**Comment by shivajipotnuru** [comment] 2021-12-09 05:07
Hi @anishprasad01
The above approach you mentioned is working fine, but we have around 1000+ links in our QnA maker. for a few answers, they are around 3-4 embedded links. as per your approach manually changing the markdown format in QnA maker is a bit difficult for us. we require a proper fix on this issue.

CC: @rajeeshmenoth

**Comment by anishprasad01** [comment] 2021-12-09 18:05
@clearab 

Do you have any insights on whether this is a bug in Teams or intended behavior, and where we might go to resolve this?

**Comment by clearab** [comment] 2021-12-09 18:33
I've reached out to them, I'll follow up here when I hear back.

**Comment by HunaidHanfee-MSFT** [comment] 2021-12-13 21:13
@anishprasad01 - Can you confirm that you can see that it's showing that its hyperlink but not working when clicking on it?

**Comment by anishprasad01** [comment] 2021-12-13 22:29
@HunaidHanfee-MSFT

Yes, that is exactly what happens. The card shows up as intended and the link is both formatted and displayed as a hyperlink, but clicking it does nothing.

For example:
![image](https://user-images.githubusercontent.com/33945547/145899163-d1aa04e6-c00b-4401-af81-8a9169aa137d.png)

**Comment by HunaidHanfee-MSFT** [comment] 2021-12-14 19:11
Thanks for the update- We have received this bug earlier as well posted by @rajeeshmenoth on StackOverflow - https://stackoverflow.com/questions/70183481/the-embeded-hyperlinks-enlarge-image-are-not-opening-in-chrome-browser-through .

Bug is already raised and fix is being tested by the team internally. The fix should pass multiple pipeline and rings to be available for public so I don't have an ETA to share as of now. But I will keep you updated about progress.

Thanks

**Comment by carlosscastro** [comment] 2022-01-24 18:42
@HunaidHanfee-MSFT closing this for now, but if you have updates feel free to re-open.

**Closed by carlosscastro** 2022-01-24 18:42 UTC
Labels: bug, customer-replied-to, customer-reported, Bot Services, Area: Teams
