### ISSUE TITLE
 Chatbot application return same response display twice in Microsoft teams

### ISSUE THREAD

**Issue by ashok-dot** [microsoft/botframework-sdk#6378] opened 2021-09-06 06:09 UTC
Hi Team,

Chatbot application return same response display twice in Microsoft teams. How to fix this issue.

Example:
Typing message like :Hi
return response :Hello
                           Hello
this two line of code using last return response.
 await stepContext.Context.SendActivityAsync(reply);
 return await stepContext.EndDialogAsync();

**Comment by dmvtech** [comment] 2021-09-06 16:11
Closing as duplicate of: https://github.com/microsoft/botframework-sdk/issues/6377

**Closed by dmvtech** 2021-09-06 16:11 UTC
Labels: bug, customer-reported, Bot Services, needs-triage
