### ISSUE TITLE
Custom Action ObjectExpression not parsed

### ISSUE THREAD

**Issue by cxbuilders** [microsoft/botframework-sdk#6123] opened 2020-11-15 13:39 UTC
When using a ObjectExpression<MyObject> in a custom action, the GetValue call does not return anything when the object is defined directly in the Custom Action itself in Composer. When using set properties before the Custom Action to define the object and use an expresssion to pass the value to the Custom Action it does work.

**Not Working:**
![image](https://user-images.githubusercontent.com/49873947/99186391-46957900-2750-11eb-8516-076fe371fdf6.png)

**Working:**
![image](https://user-images.githubusercontent.com/49873947/99186397-53b26800-2750-11eb-9165-5ca65bcf647a.png)

![image](https://user-images.githubusercontent.com/49873947/99186415-6036c080-2750-11eb-8004-4f841f0725de.png)

**Comment by GeoffCoxMSFT** [comment] 2020-12-01 18:40
Transferred to the sdk repo and marked for triage.

**Comment by EricDahlvang** [comment] 2020-12-02 05:20
I think this is by design.

**Comment by hcyang** [comment] 2020-12-02 21:38
Hi @boydc2014, per @Stevenic's comment, can you check if this issue a regression?

**Comment by EricDahlvang** [comment] 2020-12-03 02:04
@hcyang i checked 4.10, and the behavior was the same.

**Comment by cxbuilders** [comment] 2020-12-05 12:41
@EricDahlvang I have tried adding the ObjectExpressionConverter to the MyObject class, but there is no difference, it also gets never called?

@Stevenic I am now using the valueExpression in the Custom Action, with the ObjectExpression in the schema. This works great and I can do the casting myself. 

This solves my problems, so from my side it's all ok!

**Closed** 2020-12-07 09:07 UTC
Labels: Bot Services, customer-replied-to, customer-reported, needs-triage
