### ISSUE TITLE
Calling option not showing in bot conversation window in teams

### ISSUE THREAD

**Issue by kiranbudati** [microsoft/botframework-sdk#6181] opened 2021-02-02 07:51 UTC
I'm trying to build a calling bot with botframework, have enabled calling option in web bot and also, enabled supportsCalling, supportsVideo in the manifest file, but I could not find calling option in bot conversation window.

**Comment by jwiley84** [comment] 2021-02-02 17:05
Closing as a duplicate of https://stackoverflow.com/questions/65994209/mbf-calling-option-not-showing-in-teams

**Closed by jwiley84** 2021-02-02 17:05 UTC
Labels: Bot Services, customer-reported

**Comment by kiranbudati** [comment] 2021-02-03 10:24
@jwiley84  i'm the one who posted that question
