### ISSUE TITLE
Authorization has been denied for this request (Skype REST API)

### ISSUE THREAD

**Issue by pborisovich94** [microsoft/botframework-sdk#6000] opened 2020-08-24 09:35 UTC
Good evening, community experts.

I was integrating my application with Skype using the REST API (Bot Framework). Everything worked perfectly until today.
In the morning, while checking the functionality of the application, I noticed that the bot's response did not displayed in Skype. I decided to send a message through «Postman», and I received the following response:
```
{
    "message": "Authorization has been denied for this request."
}
```
I thought there might be a problem with token. Through the request below, I got a new one, but it didn't help:
```
curl -k -X POST https://login.microsoftonline.com/botframework.com/oauth2/v2.0/token -d "grant_type=client_credentials&client_id=<APP ID>&client_secret=<APP PASWORD>&scope=https%3A%2F%2Fapi.botframework.com%2F.default"
```

Here are my «Postman» POST HTTPS query settings:
```
URL:
https://smba.trafficmanager.net/apis/v3/conversations/<CONVERSATION ID>/activities/<MESSAGE ID>

HEADERS:
Postman-Token: <calculated when request is sent>
Content-Lenght: <calculated when request is sent>
Host: <calculated when request is sent>
Content-Type: application/json
Authorization: Bearer 0SzRndyIsImtpZCI6ImppYk5ia0ZTU2JteFBZck45Q0...

BODY:
{
    "type": "message",
    "from": {
        "id": <BOT ID>,
        "name": <BOT NAME>
    },
   "recipient": {
        "id": <USER ID>,
        "name": <USER NAME>
    },
    "text": <MESSAGE>
}
```

Please tell me what the problem might be? Everything worked fine yesterday! Could there be a problem with the SSL certificate? Or should the Authorization parameter be passed in some other way? Thank you in advance!

**Comment by dmvtech** [comment] 2020-08-24 22:36
As you may know bots within Skype are (are being) deprecated. Skype is scaling down their integration and support for bots. It's possible that they changed something on their backend as part of their regression. Ultimately, because we (Bot Framework) aren't in their pipeline, we have no knowledge what that might have been, _if anything_. I would suggest sending an email to skypebotsupport@microsoft.com with the MSA App ID and name of your bot, referencing this github issue and hopefully the Skype folks can look into it.

Nothing has changed in the SDK that would cause something like this.

**Comment by pborisovich94** [comment] 2020-08-26 09:12
> As you may know bots within Skype are (are being) deprecated. Skype is scaling down their integration and support for bots. It's possible that they changed something on their backend as part of their regression. Ultimately, because we (Bot Framework) aren't in their pipeline, we have no knowledge what that might have been, _if anything_. I would suggest sending an email to [skypebotsupport@microsoft.com](mailto:skypebotsupport@microsoft.com) with the MSA App ID and name of your bot, referencing this github issue and hopefully the Skype folks can look into it.
> 
> Nothing has changed in the SDK that would cause something like this.

Hello! Thanks for the answer.
Unfortunately, I faced the problem of inability to send a letter to skypebotsupport@microsoft.com due to the fact that the skypebotsupport group only accepts messages from people in its organization or on its allowed senders list, and my email address isn't on the list.

**Comment by dmvtech** [comment] 2020-08-28 18:55
Thanks @pborisovich94 

the skypebotsupport group only accepts messages from people in its organization

Ah, bummer. Sorry about that. Ok, let me see if I can find any other route/information for you.

**Comment by dmvtech** [comment] 2020-09-08 21:55
Still working on it. Stand by.

**Comment by konstlut** [comment] 2020-09-11 12:18
Hello @pborisovich94,
Please share your botid or precise time of the request so that we could correlate it in our logs.
Thank you!

**Comment by pborisovich94** [comment] 2020-09-11 12:31
> Hello @pborisovich94,
> Please share your botid or precise time of the request so that we could correlate it in our logs.
> Thank you!

Hello @konstlut,
Here is my botid: 28:47a93344-8ffc-4bd7-aa90-c63b61d1bb3e

**Comment by konstlut** [comment] 2020-09-11 13:35
Thank you, @pborisovich94. Would it be possible to reproduce the problem today? I was checking the logs from Aug, 24 but didn't find any calls made from this bot.

**Comment by pborisovich94** [comment] 2020-09-11 13:43
@konstlut Just now I tried to send an HTTP request (from Postman) and I got an 401 error again
![Снимок экрана 2020-09-11 в 15 41 27](https://user-images.githubusercontent.com/54406143/92932491-4a9dd580-f445-11ea-8218-f3ee555f9a29.png)

**Comment by konstlut** [comment] 2020-09-11 13:49
Could you you please post the full http request/response including headers (but excluding the authorization header). Thanks

**Comment by pborisovich94** [comment] 2020-09-11 13:52
@konstlut 
Everything is the same as in the message header:
```
URL:
https://smba.trafficmanager.net/apis/v3/conversations/<CONVERSATION ID>/activities/<MESSAGE ID>

HEADERS:
Postman-Token: <calculated when request is sent>
Content-Lenght: <calculated when request is sent>
Host: <calculated when request is sent>
Content-Type: application/json
Authorization: Bearer 0SzRndyIsImtpZCI6ImppYk5ia0ZTU2JteFBZck45Q0...

BODY:
{
    "type": "message",
    "from": {
        "id": <BOT ID>,
        "name": <BOT NAME>
    },
   "recipient": {
        "id": <USER ID>,
        "name": <USER NAME>
    },
    "text": <MESSAGE>
}
```

**Comment by konstlut** [comment] 2020-09-11 13:53
@pborisovich94 I would appreciate the response headers.

**Comment by pborisovich94** [comment] 2020-09-11 13:54
@konstlut 
Oh, sorry. Here they are:
![Снимок экрана 2020-09-11 в 15 54 37](https://user-images.githubusercontent.com/54406143/92933871-1b886380-f447-11ea-9802-468a94b4e67f.png)

**Comment by pborisovich94** [comment] 2020-09-16 06:50
@konstlut Hi! I apologize for distracting. Is there any information? Is there something missing in my request? Thank you in advance!

**Comment by konstlut** [comment] 2020-09-16 15:32
@pborisovich94 , please accept my apologies for the delay. Is is possible that the jwt token supplied with the request in Authorization header is missing an important part - the jwt header. Can you please doublecheck the token that is being sent with the request. Ideally you could share an example of the expired token (tokens are issued for 1 hour) here.

**Comment by pborisovich94** [comment] 2020-09-18 12:36
@konstlut God, I'm so embarrassed that I became a user who didn't bother to generate a new JWT token and test it`s work before screaming for help.
I am wildly sorry for wasting your precious time on a mediocre man like me. Through cURL, the request generated a new token, put it in the request and everything worked!
Before lagging behind you, I ask you to answer a few questions:
1. It turns out that this token needs to be replaced with a new one every 55-60 minutes when sending messages?
2. How do you assess the future of the Bot Framework and work on the REST API? Will this way of interaction continue to live? Unfortunately, the SDK does not fit our application.

Thanks a lot!

**Comment by konstlut** [comment] 2020-09-18 15:48
Hello @pborisovich94, I am happy to find you were able to resolve the issue.

` It turns out that this token needs to be replaced with a new one every 55-60 minutes when sending messages?`
Yes.

` How do you assess the future of the Bot Framework and work on the REST API? Will this way of interaction continue to live? Unfortunately, the SDK does not fit our application.` 

This is the contract and as of now it is not planned to be incompatibly changed or retired.

**Comment by dmvtech** [comment] 2020-09-22 17:56
Closing as resolved. Thanks @konstlut!

**Closed by dmvtech** 2020-09-22 17:56 UTC
Labels: Bot Services, bug, customer-replied-to, customer-reported, needs-triage
