### ISSUE TITLE
Directline v3 Getting 200 for /conversation/{id}/upload?userId={id} but no attachment in stream

### ISSUE THREAD

**Issue by ppapebright** [microsoft/botframework-sdk#6350] opened 2021-07-23 14:20 UTC
## Version
v3 directline api

## Describe the bug
The bot is sending back this message in the stream after uploading a file to the conversation via this method:
https://docs.microsoft.com/en-us/azure/bot-service/rest-api/bot-framework-rest-direct-line-3-0-send-activity?view=azure-bot-service-4.0#upload-one-attachment

"text": "Looks like you tried to send an attachment. Currently, I can only process text. Please try sending your message again without the attachment. ",

Is there some setting I need to use to get it to accept images and files?
```
{
  "activities": [
    {
      "type": "message",
      "id": "Fiq3i5iaAvEYCoARyGcUv-6|0000004",
      "timestamp": "2021-07-23T01:41:53.7085346Z",
      "channelId": "directline",
      "from": {
        "id": "2f74c4e1-339e-49d7-b673-63f61c9349af",
        "name": "DocSquad_Bot",
        "role": "bot"
      },
      "conversation": {
        "id": "Fiq3i5iaAvEYCoARyGcUv-6"
      },
      "text": "Looks like you tried to send an attachment. Currently, I can only process text. Please try sending your message again without the attachment. ",
      "inputHint": "acceptingInput",
      "attachments": [],
      "entities": [],
      "replyToId": "Fiq3i5iaAvEYCoARyGcUv-6|0000003"
    }
  ],
  "watermark": "4"
}
```

## To Reproduce
Follow steps in documentation, see OK 200 from /upload response but this message in the chat stream

## Expected behavior
No such message should appear in chat stream, and I should be able to access the uploaded media

**Comment by stevkan** [comment] 2021-07-27 17:50
Closing as a duplicate of BotFramework-Services issue #[310](https://github.com/microsoft/BotFramework-Services/issues/310).

My understanding is this is with respect to a PVA project (correct me if I'm wrong). If so, this is looking like it is an unsupported feature. Documentation has been requested from the supporting team which, if available, should be posted in the issue referenced above.

**Closed by stevkan** 2021-07-27 17:50 UTC
Labels: Bot Services, bug, customer-reported, needs-triage
