### ISSUE TITLE
Error: Get Token request returned http error: 401

### ISSUE THREAD

**Issue by AbhilashKanimilli** [microsoft/botframework-sdk#6221] opened 2021-03-01 20:14 UTC
All of a sudden my bot started to get this error:

[onTurnError] **unhandled error: Error: Get Token request returned http error: 401 and server response: {"error":"invalid_client","error_description":"AADSTS7000222: The provided client secret keys are expired.** Visit the Azure Portal to create new keys for your app, or consider using certificate credentials for added security: https://docs.microsoft.com/azure/active-directory/develop/active-directory-certificate-credentials\r\nTrace ID: 91097c7f-35a4-4f95-97bc-d616a6b45100\r\nCorrelation ID: e0110013-d13c-4897-aafc-f2e36a194ed5\r\nTimestamp: 2021-03-01 20:00:25Z","**error_codes":[7000222]**,"timestamp":"2021-03-01 20:00:25Z","trace_id":"91097c7f-35a4-4f95-97bc-d616a6b45100","correlation_id":"e0110013-d13c-4897-aafc-f2e36a194ed5","error_uri":"https://login.microsoftonline.com/error?code=7000222"}

**Comment by jwiley84** [comment] 2021-03-02 04:35
Closing as a duplicate of this: https://stackoverflow.com/questions/66429088/in-botframework-sdk-all-of-a-sudden-my-bot-started-to-get-this-error-error-get

**Closed by jwiley84** 2021-03-02 04:35 UTC
